### ISSUE TITLE
Wrong X-WindowsPhone-Target for Tile notifications

### ISSUE THREAD

**Issue by molesinski** [Redth/PushSharp#101]
SendNotification method of class WindowsPhonePushChannel decides if X-WindowsPhone-Target should be toast or token based on if notification is inheriting from WindowsPhoneTileNotification, but none of tile notification classes (Cycle, Flip and Iconinc) inherit from it.

**Comment by dungphanxuan** [comment]
Hello how can i send raw notification in php. 
Here is my header>
 $headers = array('Content-Type: text/xml', "Content-Length: " . strlen($msg), "X-WNS-Type: " . WNSTypesEnum::Raw, "Authorization: Bearer $this->access_token", "X-WindowsPhone-Target: raw", "X-NotificationClass: 3");
      
I found 400 code
