### ISSUE TITLE
Push Notification for Apple not getting sent in different Regions (Country)

### ISSUE THREAD

**Issue by Andypat1980** [Redth/PushSharp#136]
Hi Jon,

I am using PushSharp in my application for sending push notification. When i use development Certificate .p12 file then it allow me to send push notification to all Apple device inside India and don't allow me to send push notification any of the Apple device out side of India. I replaced my development Certificate with Production Certificate .p12 file. After doing this change it was working opposite. With Production Certificate .p12 file its allows me to send push notification to all device out side of India (e.g. US, Australia, S.A. etc...) , but it was getting failure for all Apple device inside India.

Do you have any idea about any setting for regions / country in Push Sharp. Or do we need to take care when we create Certificate .p12 from Apple portal ?

Sample Failure messages : 

Failure: Apple -> Exception of type 'PushSharp.Apple.NotificationFailureException' was thrown. -> {"aps": {"alert":"Bob's Notification : Hi","badge":1,"sound":"sound.caf"},"type":"text","id":9999}

Failure: Apple -> Exception of type 'PushSharp.Apple.NotificationFailureException' was thrown. -> {"aps":{"alert":"Bob's Notification : Hello","badge":1,"sound":"sound.caf"},"type":"text","id":9999}

**Comment by appscarvajal** [comment]
hi, i'm getting this issue. In development, the notifications send correcta but when the app is in production, with the distribution's certificates and with the configuration correctly in .NET.  

push.RegisterAppleService(new ApplePushChannelSettings(true ,appleCert, "PASSWORD"));

I know that Apple change the certificate`s name, and i modified the code line where the name is to Apple Push Service.

Do you have any idea about this issue ?

Thanks in advance .
