### ISSUE TITLE
Works, but always get APNS NotificationFailureException 8 : Invalid token (Linux/Mono)

### ISSUE THREAD

**Issue by trevoriancox** [Redth/PushSharp#141]
PushSharp is working very well for me on Linux/Mono, but all my Apple notifications immediately get this error, followed by a successful delivery to the device and an OnNotificationSent callback.

I've traced through the PushSharp code and it seems that this is just what Apple is sending. It's curious that "8" is also in Apple's spec as the first byte of the response, but it seems that everything is being parsed correctly.

**Comment by joaolori** [comment]
Im getting token invalid too..
Any help?

**Comment by sivakumarcse12** [comment]
I'm also getting same response

  [ERRORS] => Array
                (
                    [0] => Array
                        (
                            [command] => 8
                            [statusCode] => 8
                            [identifier] => 1
                            [time] => 1513587138
                            [statusMessage] => Invalid token
                        )

                )
