### ISSUE TITLE
APNS Certificate Woes

### ISSUE THREAD

**Issue by FirstCitizen** [Redth/PushSharp#148]
We have built a mobile application using PhoneGap and the builtin GenericPush library for push notifications.

We followed the instructions at https://github.com/Redth/PushSharp/wiki/How-to-Configure-&-Send-Apple-Push-Notifications-using-PushSharp to generate the certificate chain.  The app is compiled and deployed through phonegap, the p12 comprised of the distro ad hoc certificate and the private key.

The application successfully registers with the APNS servers and sends the deviceToken to our webserver application.

I have created a sender application using the PushSharp library that can run as a console or service.  We have ports 2195/2196 open and the certificate is granted permissions for ASPNET, Network Service, and Authenticated Users on the server (I've been testing as an authenticated user with the console).

When sending a message to APNS the application sits for a few seconds, then throws the following exception (edited for readability):

"Channel Exception: Apple -> System.ComponentModel.Win32Exception (0x80004005): The credentials supplied to the package were not recognized
{snip}
at PushSharp.Apple.FeedbackService.Run(ApplePushChannelSettings settings, CancellationToken cancelToken) 
in {snip}\PushSharp-master\PushSharp.Apple\FeedbackService.cs:line 47
at PushSharp.Apple.ApplePushService.<>c__DisplayClass2.<.ctor>b__0(Object state) 
in {snip}\PushSharp-master\PushSharp.Apple\ApplePushService.cs:line 31"

Has anyone had experience using PushSharp with PhoneGap/GenericPush?

It seems that the connection is being made but fails when setting up the feedback service.  Having followed the certificate creation recommendations, and the certificate working correctly on the application side to communicate with APNS for it's deviceToken, leaves me at a loss about where the issue might be at.

Thanks for making the PushSharp library available!  It's been a tremendous help in this project.

**Comment by deansyd** [comment]
My colleague and I followed the guide above. But on step 12, we selected the Certificate only not the Private key and exported it. And it worked.
