### ISSUE TITLE
GCM Notification Sent Message Event Failing to Fire

### ISSUE THREAD

**Issue by chrissadams** [Redth/PushSharp#150]
I'm sure I'm doing something stupid, but I failing to get a GCM OnNotificationSent event to fire.

I setup the broker as:-

 broker = new PushBroker();

```
            broker.RegisterGcmService(new GcmPushChannelSettings(this.SenderAuthToken));

            broker.OnDeviceSubscriptionExpired += new PushSharp.Core.DeviceSubscriptionExpiredDelegate(this.Broker_OnDeviceSubscriptionExpired);
            broker.OnDeviceSubscriptionChanged += new DeviceSubscriptionChangedDelegate(Broker_OnDeviceSubscriptionChanged);
            broker.OnNotificationFailed += new PushSharp.Core.NotificationFailedDelegate(Broker_OnNotificationFailed);
            broker.OnNotificationSent += new NotificationSentDelegate(Broker_OnNotificationSent);
            broker.OnServiceException += new ServiceExceptionDelegate(Broker_OnServiceException);
```

The event handler method is defined as 

 private static void Broker_OnNotificationSent(object sender, INotification notification)
        {
            Core.Diagnostics.Logger.Info("GCM Notification Sent Event Fired {0}", notification);  
        }

I don't get any logging out and any breakpoints on this method aren't hit.

Am I doing something wrong?

**Comment by memark** [comment]
I ran in to this today (on a system using version 2). It was really tricky to find this post.
