### ISSUE TITLE
too many "The maximum number of Send attempts to send the notification was reached!"

### ISSUE THREAD

**Issue by jjangg96** [Redth/PushSharp#155]
I usually send 1000 messages a minute.
It seems work well, but sometime there is sending problem without any notify message, then I have to re run programs.

I recently change setting value.
PushServiceSettings pushSetting = new PushServiceSettings();
pushSetting.AutoScaleChannels = true;
pushSetting.MaxNotificationRequeues = 10;
pushSetting.MaxAutoScaleChannels = 256;
pushSetting.NotificationSendTimeout = 60000;

Still have "The maximum number of Send attempts to send the notification was reached!" problem 5~10 times a minute, not always.  
I have 2 PushBroker instance threads. Does it any relation?

Thank you for reading.

![ 2013-04-16 3 39 16](https://f.cloud.github.com/assets/927149/384667/6bba3e9c-a660-11e2-945e-503942a787af.png)

**Comment by suja-balan** [comment]
@ogborstad @Redth 
Hi all
Iam a .net developer and for push notification iam using Pushsharp 2.2.1.0 .For android it is working fine and the issue is in IOS.
    #region Iphone push notification
                    //IPhone push notification
                    if (iOSTokenList != null && iOSTokenList.Any())
                    {
                        ////sandbox = true in production environment. In development set "sandbox = false"
                        string p12File = WebConfigurationManager.AppSettings["notificationCertificateName"].ToString();   //Certificate name
                        string p12FilePassword = WebConfigurationManager.AppSettings["notificationPassword"].ToString(); ;  //Password
                        string isProductionFlag = WebConfigurationManager.AppSettings["notificationIsProduction"].ToString();  //Production/Sandbox true=Production,false=sandbox

                        bool isProduction = true;
                        bool.TryParse(isProductionFlag, out isProduction);
                        String p12Filename = HostingEnvironment.MapPath("~/" + p12File); ;

                        var settings = new PushServiceSettings();
                        settings.AutoScaleChannels = false;
                        settings.MaxAutoScaleChannels = 20;
                        settings.MinAvgTimeToScaleChannels = 100;
                        settings.Channels = 1;
                        settings.MaxNotificationRequeues = 25;
                        settings.NotificationSendTimeout = 15000;
                        //settings.IdleTimeout = TimeSpan.FromMinutes(5);

                        push.RegisterAppleService(new ApplePushChannelSettings(isProduction, p12Filename, p12FilePassword, true), settings);
                        var pushPayload = new AppleNotificationPayload();
                        //  pushPayload.AddCustom("PayLoad", ApplePayload);
                        foreach (var iosDeviceToken in iOSTokenList)
                        {
                            if (iosDeviceToken != null && !string.IsNullOrWhiteSpace(iosDeviceToken.DEVICE_ID) && iosDeviceToken.DEVICE_ID.Length == 64)
                            {
                                try
                                {
                                    var alertNotification = new AppleNotification()
                                    .ForDeviceToken(iosDeviceToken.DEVICE_ID)
                                    .WithAlert(iosDeviceToken.SUBJECT)
                                    .WithSound("default");
                                    //.WithPayload(pushPayload);
                                    //.WithBadge(0);
                                    alertNotification.Payload.Alert = new AppleNotificationAlert() { Body = iosDeviceToken.SUBJECT };
                                    //service.QueueNotification(alertNotification);
                                    push.QueueNotification(alertNotification);
                                    noOfSuccess++;



                                }
                                catch (Exception ex)
                                {
                                    ErrorLogging.LogError("Exception while pushing notification for ios :-" +ex.Message +"for device id:-"+ iosDeviceToken.DEVICE_ID);
                                    response = ex.Message;
                                  
                                }
                            }
                              
                            else
                            {
                                ErrorLogging.LogError("Invalid Device Token");
                                response = "Invalid Device Token";
                               
                            }
                         
                        }
                        push.StopAllServices(true);
                    }
                    #endregion Iphone push notification


The above code is used for ios push notification.
But iam getting error "The maximum number of Send attempts to send the notification was reached!"

Can anyone please help me to sort out this?. It is really a critical issue.
