### ISSUE TITLE
Apple Push - Production Certificate error:  Status code 8

### ISSUE THREAD

**Issue by StyvieK** [Redth/PushSharp#196]
Is there any way to tell what the error status code 8 means in "HandleFailedNotification" ?

Development push works as expected.  

With my production cert,  and the Production Flag selected, all the checks and validations run fine, and the certificate validates as a Production certificate. 

The notifications fail, and I can see the status code 8 in the HandleFailedNotification method.

**Comment by Sakthimuthiah** [comment]
Hi, I have created ios app which is using AWS SNS service for notification. I have created an ipa for Adhoc distribution with development provisioning profile, development certificate, configured AWS SNS Application with "Apple Development" push platform. IOS app successfully created "Endpoint Arn and Subscription under Topic". Problem is "If i send notification then endpoint arn "Enabled flag" automatically changes to "False", aws log info tells that Status code: 8 - Invalid token. How to fix it ? Please help. Advance thanks.
