### ISSUE TITLE
Strange error: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full

### ISSUE THREAD

**Issue by dehaaneric** [Redth/PushSharp#214]
Hi everyone,

After almost two weeks of nonstop, succesful pushing (40.000+ push messages sent), suddenly we received the following error:

```
Failure: PushSharp.Android.GcmPushService -> Unable to connect to the remote server

Message :An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full
Source :System
Stack Trace :   at System.Net.Sockets.Socket.DoBeginConnect(EndPoint endPointSnapshot, SocketAddress socketAddress, LazyAsyncResult asyncResult)     
at System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Int32 timeout, Exception& exception)
TargetSite :Void DoBeginConnect(System.Net.EndPoint, System.Net.SocketAddress, System.Net.LazyAsyncResult)
```

After this error occurred, other Windows Services also couldn't connect anymore to other services (external mail relay service, external blacklist check). 

Still, it's a very generic error, so I might not have to do with PushSharp. But, when I restarted the Windows Service (so, releasing all resources I guess) everything, all other Windows Services worked again. To put it simple, it looked like the Pushservice had a lock on all TCP channels or something like that.

OS information: Windows Server 2003 Enterprise x64

I hope I can get some help to solve this issue, for myself and future PushSharp users.

Many thanks in advance.

**Comment by duaneking** [comment]
What was the change made to fix this?
