### ISSUE TITLE
PushSharp.WindowsPhone seems to stops working after a long idle

### ISSUE THREAD

**Issue by mcastrillo** [Redth/PushSharp#245]
Hi,

I'm experiencing some troubles to get PushSharp.WindowsPhone working on production server after a long time of inactivity, and I have tried stable and beta versions.

I'm working with a webservice that send notifications for android and windows phone, android notifications works like a charm, but for windows phone, after a long time of inactivity, I can only get a "PushSharp.WindowsPhone.WindowsPhoneNotificationSendFailureException", and when I restart the web server service, the problem dissapears. To start PushSharp on my service, I have the follow code on Application_Start event, inside Global.asax:

            var store = new X509Store(StoreName.My, StoreLocation.LocalMachine);
            store.Open(OpenFlags.ReadOnly | OpenFlags.OpenExistingOnly);
            var certificate = store.Certificates.Find(X509FindType.FindByThumbprint, ".....", false)[0];
            store.Close();

            WindowsPhonePushChannelSettings wps = new WindowsPhonePushChannelSettings(certificate);
            ColaNotificaciones.RegisterWindowsPhoneService(wps);

            ColaNotificaciones.RegisterGcmService(new GcmPushChannelSettings("......"));

(ColaNotificaciones is a static public PushSharp.PushBroker object), and on Application_End event (the only line on event):

```
ColaNotificaciones.StopAllServices(true);
```

If can be help, this line causes the follow exception:

```
System.Core
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.ForAllOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at servicio.Global.Application_End(Object sender, EventArgs e) in c:\bitcult\SumSumZero\Servicio\Global.asax.cs:line 26

Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
```

After the webservice starts, all work perfectly, but after various "automatic" restarts of the service, the WindowsPhone library starts to fail with the exception "PushSharp.WindowsPhone.WindowsPhoneNotificationSendFailureException", while Android GCM still working. It's happening with various users, with various WP devices. If I get back again to my old webservice, before the implementation of PushSharp, all works fine, but I'm very interested to get PushSharp working since I'm planning to start a iphone port of my app and PushSharp sound like a dream to maintain all those push services providers.

I really don't know if this may help, but I noticed that channel on Android is created and destroyed only one time, and windowsphone occurs various times

```
Channel Destroyed for: PushSharp.Android.GcmPushService
Channel Destroyed for: PushSharp.WindowsPhone.WindowsPhonePushService
Channel Destroyed for: PushSharp.WindowsPhone.WindowsPhonePushService
Channel Destroyed for: PushSharp.WindowsPhone.WindowsPhonePushService
Channel Destroyed for: PushSharp.WindowsPhone.WindowsPhonePushService
Channel Destroyed for: PushSharp.WindowsPhone.WindowsPhonePushService
Channel Destroyed for: PushSharp.WindowsPhone.WindowsPhonePushService
```

I don't know if I'm missing something important or it may be a pushsharp issue.

Thanks

**Comment by esskar** [comment]
is there something you did to make it work?

**Comment by altima** [comment]
Hi,

in my case, the used .NET framework was the Mono stuff and this has an error in dns resolver class. it will not resolve right ip address for socket connections after DNS TTL timeout. 

Otherwise I created an new push channel for windows phone. The default channel does not utilize the waitCounter logic (Interlocked signature) that was implemented in GCM channel for example. I can provide my created windows phone channel stuff, if needed.

My push server, that runs on Debian via Mono (currently 3.10), works now since October 2014 without any problems and downtime.

I use iPhone, Android (C2DM,GCM), Windows Phone and Amazon channels. :)

**Comment by esskar** [comment]
can you show me your creation code?

**Comment by altima** [comment]
Hey, sorry for the delay, i forgot to answer... :(

here are my windows phone stuff, that work on my side with mono 3.10

https://gist.github.com/altima/2db84b57ef3ecdf4f887

**Comment by altima** [comment]
and also the custom amazon snippets: https://gist.github.com/altima/2c65755bb3e16d43625d

**Comment by esskar** [comment]
thanks, i will check that out
