### ISSUE TITLE
'System.MissingMethodException'

### ISSUE THREAD

**Issue by mhoberhausen** [Redth/PushSharp#316]
I opened a case up for this before but it was closed because I did not have addition information (and i can't reopen). Here's what I'm getting when sending an GCM message:

A first chance exception of type 'System.MissingMethodException' occurred in PushSharp.Android.dll
Failure: PushSharp.Android.GcmPushService -> Method not found: 'System.Collections.Generic.IEnumerator`1 Newtonsoft.Json.Linq.JArray.GetEnumerator()'. -> {
"registration_ids": [
""
],
"data": {
"UTILITY": "{\"messageID\":10968402,\"driverID\":37,\"latitude\":41.3871,\"longitude\":-72.8739,\"msgText\":\"694-601-S - 21-REST4 ¿76 STATE STREET¿NORTH HAVEN CT 06473¿\",\"dateCreated\":\"1/17/2014 9:30:01 AM\",\"jobID\":\"694-601-S\",\"jobStatus\":\"Undelivered\",\"msgType\":\"W\",\"sender\":\"\",\"insightID\":-1,\"igiMsg\":\"JOB|-1|1|694-601-S - 21-REST4 
76 STATE STREET
NORTH HAVEN CT 06473
|41.3871|-72.8739|10|694-601-S\",\"msgResponse\":\"\"}"
}
}

**Comment by Raveendra-Pai** [comment]
AidanHost, which particular version you tried ?

**Comment by AidanHost** [comment]
@Raveendra-Pai I have no idea, this was almost 4 years ago. I imagine that I would have downloaded the latest version at the time.

**Comment by Raveendra-Pai** [comment]
I uninstalled Newton.Json.dll from GAC. Then there was no error. It was loading local Newton.Json.dll. started working fine.
