### ISSUE TITLE
AdHoc certificate with Pushsharp

### ISSUE THREAD

**Issue by menasheu** [Redth/PushSharp#358]
Hi,
I am working with Pushsharp in a C#/IIS project and everything works fine in the development phase with iOS devices. When trying to test with testers devices with an adHoc certificate, putting true as the first parameter of  ApplePushChannelSettings, I receive a message in the server saying "You have selected the Production server, yet your Certificate does not appear to be the Production certificate!  Please check to ensure you have the correct certificate!" although I do have the adHoc certificate in the server.
Do you have any idea?

**Comment by davidpaul0880** [comment]
When you give production certificate (.p12) to .Net server team, Always export like selecting the certificate only. see the attached image  
![screen shot 2016-02-15 at 1 10 21 pm](https://cloud.githubusercontent.com/assets/5885630/13042456/5ade566a-d3e6-11e5-9d8f-1318bc5fffef.png)

**Comment by flipdish** [comment]
Future Googlers: Fastlane PEM creates certs named 'Apple Push Services' which will fail the PushSharp validation. So you must disable validation for these certs.

**Comment by Redth** [comment]
PushSharp 4.x does support this new common name, so it should work without disabling validation.

**Comment by menasheu** [comment]
Where do we find the PushSharp version number? In Readme.md?
