### ISSUE TITLE
Newtonsoft Json.Net hard dependency causing problems

### ISSUE THREAD

**Issue by dylanvdmerwe** [Redth/PushSharp#361]
Json.Net is sitting on version 6.0.1 and many people use NuGet to ensure their versions are up to date. It seems that PushSharp has a dependency on version 4.5.0 which is causing exceptions to be thrown at run time. Surely there must be a way to prevent PushSharp library from causing this kind of chaos without having to remap the binary in the app config. I'm using the latest stable version 2.0.4.

3>  No way to resolve conflict between "Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" and "Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed". Choosing "Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" arbitrarily.
3>  Consider app.config remapping of assembly "Newtonsoft.Json, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" from Version "4.5.0.0" [Newtonsoft.Json.dll] to Version "6.0.0.0" [Newtonsoft.Json.dll] to solve conflict and get rid of warning.

**Comment by matthewcanty** [comment]
Forcing reinstall fixed all problems for me. Maybe this ticket should be closed?

    Uninstall-Package Newtonsoft.Json -Force
    Install-Package Newtonsoft.Json

**Comment by jahansha** [comment]
the above did not work for me. eventually I got it to work by going to references  section in project and locating the directory where Newtonsift.Json.dll was located. [it was in a folder...\dependencies\] I copied a version 6.0.0 over it. and it worked..

**Comment by bobparker58** [comment]
You must in NuGet reintall or downgrade version Newtonsoft.Json. See how I did it: https://pro-papers.com/
