### ISSUE TITLE
PushSharp : System.Net.Sockets.SocketException 

### ISSUE THREAD

**Issue by ashish14Mohan** [Redth/PushSharp#376]
Hello ,

I am using push sharp 2.1.2.0 for sending message to apple. I am receiving some message but  some message are missing.

sometimes  alerts are reaching too late in device

I am getting following error when sending the message sometimes  .

PushSharp.Apple.ApplePushService -> System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 17.149.34.188:2196
   at System.Net.Sockets.TcpClient..ctor(String hostname, Int32 port)
   at PushSharp.Apple.FeedbackService.Run(ApplePushChannelSettings settings, CancellationToken cancelToken) in UHS.App.Services.Notification.GCMIOS\GcmIOS\FeedbackService.cs:line 60
   at PushSharp.Apple.ApplePushService.<>c__DisplayClass4.<.ctor>b__1(Object state) in 
ApplePushService.cs:line 51

my code is as follows

 push = new PushSharp.PushBroker();
            push.OnNotificationSent += NotificationSent;
            push.OnChannelException += ChannelException;
            push.OnServiceException += ServiceException;
            push.OnNotificationFailed += NotificationFailed;
            push.OnDeviceSubscriptionExpired += DeviceSubscriptionExpired;
            push.OnDeviceSubscriptionChanged += DeviceSubscriptionChanged;
            push.OnChannelCreated += ChannelCreated;
            push.OnChannelDestroyed += ChannelDestroyed;
            string password = System.Configuration.ConfigurationManager.AppSettings["Password"].Trim();
            string filepath = System.Configuration.ConfigurationManager.AppSettings["FilePath"].Trim();
            var appleCert = File.ReadAllBytes(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, filepath));
            try
            {
                push.RegisterAppleService(new ApplePushChannelSettings(appleCert, password));
            }
            catch (Exception ex)
            {
            }

following code to queue up the Message .

push.QueueNotification(new AppleNotification().ForDeviceToken(DeviceID).WithAlert(Message).WithBadge(1));

Please suggests the solutions for this Issue
Thanks 
Ashish

**Comment by pranaydutta89** [comment]
:+1:
