### ISSUE TITLE
Is there a Win/WP 8 and 8.1 example?

### ISSUE THREAD

**Issue by biapar** [Redth/PushSharp#386]
Is there a Win/WP 8 and 8.1 example?

**Comment by JRMalherbe** [comment]
Where do I specify the Client Secret, needed to connect to WNS

**Comment by JRMalherbe** [comment]
I used the WindowsService to send to Windows Phone 8.1

`push.RegisterWindowsService(new WindowsPushChannelSettings("Your Package Name", "Your Client SID", "Your Client Secret"));
`
push.QueueNotification(new WindowsToastNotification()
				.AsToastText01("This is a test")
				.ForChannelUri("Your Uri"));
`

**Comment by JRMalherbe** [comment]
I used the WindowsService to send to Windows Phone 8.1

`pushBroker.RegisterWindowsService(new WindowsPushChannelSettings("Your Package Name", "Your Client SID", "Your Client Secret"));
`
`pushBroker.QueueNotification(new WindowsToastNotification()
.AsToastText01("This is a test")
.ForChannelUri("Your Uri"));
`

**Comment by rspl17** [comment]
@JRMalherbe  

Can you tell me from where did you get "Client SID", "Your Client Secret". 

Right now I didnt able to send notifications to windows phone.

**Comment by JRMalherbe** [comment]
Expand your App on  dev.windows.com (Dashboard). Expand [App management] and select [App identity]. It is now called the [Package SID].

**Comment by rspl17** [comment]
@JRMalherbe 

and for testing purpose is it neccesary for now ?
I mean following the sample code doesnt work

**Comment by JRMalherbe** [comment]
@rspl17 yes it is necessary. Push notifications won't work without an App entry in the dashboard. You only need the App entry for testing, you don't need to deploy. Reserve you App Name and locate your Package SID.

**Comment by rspl17** [comment]
@JRMalherbe  For that I guess I need to have a Paid Developer Account
