### ISSUE TITLE
APNS: SCHANNEL / TLS settings influence ability to connect.

### ISSUE THREAD

**Issue by samkelleher** [Redth/PushSharp#387]
When using PushSharp locally to connect to relay notifications to APNS only, I can see the process (in this case an asp.net website) established two connections to Apple on ports 2195 and 2196 as normal (running Windows 8.1).

In the server environment of Windows Server 2012 R2; the process is establishing hundreds of connections to APNS over and over, continuously, while not actually delivering any notifications - nothing works.

In the event log, there is a Schannel error only that happens continuously, and stops occouring if I stop the website:

> A fatal alert was received from the remote endpoint. The TLS protocol defined fatal alert code is 40. Schannel Event ID 36887

This server has had it's TLS cyphers adjusted to the websites hosted in IIS do not serve using insecure cyphers, I.e. SSL 2 and SSL 3.

It appears that APNS may be secured using one of these ciphers and hence won't work.

This is written more of a guidance than anything.

**Comment by amitmittal** [comment]
I am getting same error as joelrb was getting. APNS works well on my dev windows 10 machine but not on Windows server 2012 standard. Here is a link to send test notification from our development server http://52.63.179.100/merchant/sendapplepush

I'll try joelrb workaround and see if it works for me.

By the way, i am using PushSharp 4

**Comment by jlubeck** [comment]
@amitmittal how did you assign the permissions to IIS Application User?
