### ISSUE TITLE
Emoji icons in alert is escaped

### ISSUE THREAD

**Issue by bitified** [Redth/PushSharp#397]
When I send emoji icons as alert with AppleNotificationPayload, it is just displayed on ios device as text (like: ﻿\ud83d\ude09).

I'm not sure if this is the problem, but when taking my AppleNotificationPayload object, toJson(), I can see that my alert (the emojis) is escaped with backslash. This is the json output:

{"aps":{"alert":"user commented: great \\ud83d\\ude09"}}

How to do this without getting the emojis escaped?

I guess it would work if I got this as output
{"aps":{"alert":"user commented: great \ud83d\ude09"}}

**Comment by averagemale** [comment]
Yea, almost 2 years and no replies? Hello?

**Comment by rupe120** [comment]
This isn't a PushSharp bug. 

https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/TheNotificationPayload.html

From the comment on the Alert field:
`https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/TheNotificationPayload.html`
