### ISSUE TITLE
PushSharp.Android.GcmPushService -> Unable to connect to the remote server

### ISSUE THREAD

**Issue by AjayKN** [Redth/PushSharp#436]
Dear Friends,

The application tested some time back where we used recieve messages at mobile end, now we are recieveing error "PushSharp.Android.GcmPushService -> Unable to connect to the remote server" 

Please guide me what could be wrong 

Thanks and Regards,
Ajay K N

**Comment by TimothyY** [comment]
Just sharing my experience here,

I got the same error and in my case, there was a wrong network configuration at the server side that cause the message to be unable to reach google. 

I'm using two gateway at my server in which both are set as default and this might affect the data transfer flow. (only one should be default at the same time)

Also somehow my server internet connection bandwith is not sufficient (0 MB) which also affect the data transfer.
