### ISSUE TITLE
Can't retrieve device token from INotification

### ISSUE THREAD

**Issue by savissimo** [Redth/PushSharp#441]
In event callbacks like NotificationFailed I can't get the device token the callback refers to. The callback receives an INotification object, and I could cast this to either an AppleNotification (and get the DeviceToken) or a GcmNotification (and get RegistrationIds), but this is ugly. 

Would it make sense to add a getter for the device token in the INotification interface? Otherwise, could the token be passed as an argument to the callbacks?

**Comment by jeromeliger** [comment]
Maybe it's because the GCM can send the same notification to multiples RegistrationID...
And personnaly, I don't see what is so "Ugly"...

```C#

private void NotificationSent(object sender, INotification notification)
{
     #region GCM
     if (notification.GetType().Name == "GcmNotification")
     {
        GcmNotification GoogleNotif = notification as GcmNotification;
        foreach (string RegID in GoogleNotif.RegistrationIds)
        {
            //string RegistrationID = RegID;
        }
    }
    #endregion
    #region APNS
    else if (notification.GetType().Name == "AppleNotification")
    {
        AppleNotification AppleNotif = notification as AppleNotification;
        //string RegistrationID = AppleNotif.DeviceToken;
    }
    #endregion
    #region WPNS
    else if (notification.GetType().Name == "WindowsPhoneToastNotification")
    {
         WindowsPhoneToastNotification WP_Notif = notification as WindowsPhoneToastNotification;
         //string RegistrationID = WP_Notif.EndPointUrl;
     }
    #endregion
}

```

regards

**Comment by savissimo** [comment]
Well, for being ugly... OOP is exactly meant to avoid if-else branches like that one. I'd expect a virtual method in the base class whose implementation is defined in each derived class. 

You're correct about multiple IDs, and that is exactly why I would love to know which one caused the error. If I send a notification to 1000 "devices", then get an "invalid device token" error callback, how could I know which device token is invalid?

**Comment by jeromeliger** [comment]
A way with Android is to create/send 1 notification for only 1 device ID... 
That's what I've done exactly for the same reason that you talk about.

I don't think this is the best way... maybe ugly... but It works fine.
;-)

**Comment by smurfpandey** [comment]
It seems the events are raised for each registrationId. https://github.com/Redth/PushSharp/blob/master/PushSharp.Android/Gcm/GcmPushChannel.cs#L231

So, if you are sending notification to 1000 devices, you will get 1000 notificationsent/notificationfailed events. 

Regarding expired device token, the library is making sure to send 1 event per expired token. So if 20 tokens are expired you will get 20 different DeviceSubscriptionExpired events.
