### ISSUE TITLE
Apple pushes Not Working

### ISSUE THREAD

**Issue by kharerakesh** [Redth/PushSharp#448]
Every thing is working for me since last week from couple of months , and now it start giving error "Maximum number of attempts (3) to connect to gateway.push.apple.com:2195 was reached!", i read few notes on Git so i updated my library ,but it still not working for me with the latest TLS changes , i am using windows server 2012 R2.
i cross checked my certificate and its working on my Development PC win 8 , the ports are Open on server. please help!!..

Waiting for Queue to Finish...
Channel Created for: PushSharp.Apple.ApplePushService
Failure: PushSharp.Apple.ApplePushService -> Exception of type 'PushSharp.Apple.
NotificationFailureException' was thrown. -> {"aps":{"alert":"Hello World!","bad
ge":7,"sound":"sound.caf"}}
Queue Finished, press return to exit...

**Comment by Xollie** [comment]
I cant get the apple push notification to work i don't know what m doing wrong, I did the certificate part a thousand times, checked if ports are opened but nothing happens, got the device token but still cnt make it work i don't receive my ant notification and i don't know what m doing wrong
