### ISSUE TITLE
PushSharp depends on BCL packages even when targetting .Net Framework 4.5

### ISSUE THREAD

**Issue by julealgon** [Redth/PushSharp#451]
After the 2.1.X version, a dependency was added to the BCL packages (specifically the http://www.nuget.org/packages/Microsoft.Net.Http one, which carries the other BCL packages as dependencies with it), I assume because of the use of .Net4.5 specific constructs like async/await on the .Net4.0.

The problem though is that these dependencies are also present when a .Net 4.5 project references PushSharp. These BCL packages are extremely intrusive (they change the csproj files, add various bindingredirects to the web/app.config, etc).

When the BCL packages are needed, it is common to make different compilations for the two different target frameworks: one for .Net 4.0, with the BCL packages as dependencies, and another for .Net 4.5, which does not need them. I kindly ask that the project be compiled to .Net4.5 without the BCL dependencies so that people with the newer framework can have a cleaner project without these redundancies and unnecessary dlls. This can be configured on the same nuget package, similar to this one:
https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client

![capture](https://cloud.githubusercontent.com/assets/461579/4982327/f2add2cc-6911-11e4-84a7-9fb86f3a079a.PNG)

Notice that when targeting .Net4.5 the BCL packages are not dependencies.

We have decided to stay with 2.0.4 for the moment for this very reason.

**Comment by RichardAllanBrown** [comment]
This is an issue I'm having, using TFS Build with BCL is a real annoyance (you can quickly resolve it by setting clean workspace to only clean outputs, but this can have unintended side effects).
