### ISSUE TITLE
Notification Failure: PushSharp.Blackberry.BlackberryPushService -> Value cannot be null.

### ISSUE THREAD

**Issue by seantack** [Redth/PushSharp#456]
I have yet to see a working sample for BlackBerry.  I tried following suit with the other platforms, but I get a 'notification failure' event.  Though the PushBroker.RegisterBlackberryService method appears to have the latter 2 parameters defaulted to null it doesn't seem to like such.  However, if I pass new objects for these parameters I get the same issue.

pushBroker.RegisterBlackberryService( new BlackberryPushChannelSettings( "ourAppIdHere", "outPwdHere" ) );

If there is some working sample code for BB that would be great.  I opened another issue on that.

Any assistance would be greatly appreciated.

**Comment by JRMalherbe** [comment]
I got one to work. Here are the steps I followed

`BlackberryPushChannelSettings bbSettings = new BlackberryPushChannelSettings("App ID", "Push Password");`
`bbSettings.OverrideSendUrl("https://cpxxxx.pushapi.eval.blackberry.com"); //our eval url`
`push.RegisterBlackberryService(bbSettings, null, null);`

`BlackberryNotification bbNotification = new BlackberryNotification();`
`bbNotification.Recipients.Add(new BlackberryRecipient("Device ID"));`
`bbNotification.Content = new BlackberryMessageContent("PushSharp Message");`
`bbNotification.SourceReference = "App ID"; //again, as above`
`push.QueueNotification(bbNotification);`
