### ISSUE TITLE
WindowsPhone firing 6 events for a single WindowsPhoneToastNotification notification

### ISSUE THREAD

**Issue by benamada** [Redth/PushSharp#457]
When using the boilerplate code:

    pushBroker.RegisterWindowsPhoneService();
    pushBroker.QueueNotification(new WindowsPhoneToastNotification()....);

I get 6 of each of the following events firing: `ChannelCreated`, `NotificationSent`, `ChannelDestroyed`.

It looks like it's related to the fact that `RegisterWindowsPhoneService` registers 6 separate Windows Phone services ([source](https://github.com/Redth/PushSharp/blob/master/PushSharp.WindowsPhone/WindowsPhonePushBrokerExtensions.cs)).

**This doesn't seem right that I'm queuing a single `WindowsPhoneToastNotification` notification, but events for these other 5 services are firing** (`WindowsPhoneCycleTileNotification`, `WindowsPhoneFlipTileNotification`, `WindowsPhoneIconicTileNotification`, `WindowsPhoneTileNotification`, `WindowsPhoneRawNotification`).

As a workaround, rather than calling `RegisterWindowsPhoneService`, I'm using the following code from [this closed issue](https://github.com/Redth/PushSharp/issues/351):

    pushBroker.RegisterService<WindowsPhoneToastNotification>(
        new WindowsPhonePushService(new WindowsPhonePushChannelSettings()));

With the above code, these events only fire 1 time, which is the expected behavior.

I'm on PushSharp v2.2.0.

**Comment by jeromeliger** [comment]
I got exactly the same problem... OnNotificationSend is fired 6 times.

I'm on a WindowsPhone 8.1 Silverlight development for the mobile, and I use the RegisterWindowsPhoneService(); for the server.
I confirm there is actually 5 others service (CycleTile, FlipTile, IconicTile, Tile and Raw) running (and in this "bug", each is firing the NotificationSend.

I'm gona test the RegisterService<WindowsPhoneToastNotification>()...
Thank you Benamada for the workaround, that what I'm looking for.
