### ISSUE TITLE
The maximum number of Send attempts to send the notification was reached!

### ISSUE THREAD

**Issue by manojpaul2006** [Redth/PushSharp#462]
Hello,

Can anybody know why I am getting this message?

The maximum number of Send attempts to send the notification was reached!

Thanks in advance.

**Comment by adozenlines** [comment]
No solution to this one as yet just ran into to issue myself as well, gonna dig through the source and see what's is up...

**Comment by YARG** [comment]
For the time being I've given up on this but if you manage to sort it out adozenlines that would be fantastic!

**Comment by adozenlines** [comment]
might have something to do with how certs are now handled.
https://support.microsoft.com/en-us/kb/901183/en-us

**Comment by adozenlines** [comment]
What i found in the source for Apple push channels was the X509Certificate instead of X509Certificate2 versions of the API also for the collection methods. Something is going wrong during the handshake causing Apple to close the connection. The very first time i tried this it worked then a few days after this was the problem.

**Comment by adozenlines** [comment]
@YARG - fixed
You basically need to supply your own PushServiceSettings and attach it to the RegisterAppleService
This few lines of code extended the queue resend attempts
            var serviceSettings = new PushServiceSettings();
            serviceSettings.MaxNotificationRequeues = 100;

            push.RegisterAppleService(settings, serviceSettings);

**Comment by YARG** [comment]
Well done ADozenLines!  I'll have a look on Monday to confirm that the fix works for us as well.

Cheers!

**Comment by adozenlines** [comment]
Here is what I did.
1. Exported Apple Developer & Distribution Certificates as *.p12 from Keychain of Mac (No Private Keys)
2. Added the certificates to the windows keychain of server under personal & trusted roots to match the certs being loaded for the push channel settings
3. Extended the max re queue property value of service settings to 25, the default is 5

Each notification is now delivered successfully.

Problem fixed.

**Comment by ffchris** [comment]
Agreed with adozenlines. 

We had a similar issue. The issue ended up being that when exporting the p12 we multi selected to export public and private to generate the p12. When only exporting the public, the size of the p12 was 3217 bytes. The 3217 byte file worked. If your p12 is 6140 bytes you'll need to regenerate it.

**Comment by YARG** [comment]
Thanks Chris,  sadly my client has pulled the project due to them not making any money with their idea but it's still on my list to look and I will update this when I can with my findings.    Hope you have a good weekend.

**Comment by josfalme** [comment]
Thanks @ffchris ! it worked perfectly!
