### ISSUE TITLE
PushBroker.QueueNotification silently failing if abstract type is passed

### ISSUE THREAD

**Issue by tj81** [Redth/PushSharp#475]
I spend a whole day on a very (C#-)unexpected bahavior:
If I call "PushBroker.QueueNotification" with a "PushSharp.Core.Notification" object, it silently fails and just does NOTHING.
After debugging through PushSharp I found out that this is caused by the "generic" nature of "QueueNotification": It can't resolve the concrete type of the passed object.
Some code to illustrate what I was trying to achieve:

public abstract class MyNotification {
  public abstract PushSharp.Core.Notification Create();
}
public class MyGCMNotification : MyNotification{
  public override PushSharp.Core.Notification Create() {
    return new new NotificationGCM(...);
  }
}

public void Add(AMyNotification n) {
  pushBroker.QueueNotification(n.Create());  // Just does nothing
}

Catching this at compile-time might be difficult. But maybe an exception or error-return could save others some time here(?)

**Comment by alistefano** [comment]
I encountered the same issue. I built this method to send generic notifications:

private Notification ConvertToPushSharpNotification(PushNotification genericNotification)
        {
            Notification notif = null;
            switch (genericNotification.Provider)
            {
                case Provider.Apple:
                    notif = new AppleNotification().ForDeviceToken(genericNotification.PushId).WithCustomItem("data", genericNotification.Data);
                    break;

                case Provider.Android:
                    notif = new GcmNotification().ForDeviceRegistrationId(genericNotification.PushId)
                        .WithJson(genericNotification.Data);
                    break;

                case Provider.WindowsPhone:
                    notif =
                        new WindowsPhoneRawNotification().ForEndpointUri(new Uri(genericNotification.PushId))
                            .WithRaw(genericNotification.Data);
                    break;
            }
            return notif;
        }

When I call broker.QueueNotification(notif) it silently fails. 
I lost all my day for this issue. Please resolve this unexpected behaviour that breaks the polymorphism rule.
