### ISSUE TITLE
Different versions Newtonsoft.Json

### ISSUE THREAD

**Issue by eabdullin** [Redth/PushSharp#479]
Hi! if we have a different versions of Newtonsoft.Json in, for example, ASP.Net Mvc application then we will get a problem like this
http://stackoverflow.com/questions/13871806/pushsharp-notifications-to-apples-apns-not-working-not-throwing-any-exceptions

**Comment by ADNewsom09** [comment]
Confirmed I can reproduce this error also.

**Comment by embassem** [comment]
you can update your  Newtonsoft.Json to the latest one  be aware  to update it's section in web.config
