### ISSUE TITLE
APNS broadcast

### ISSUE THREAD

**Issue by sasirekhak** [Redth/PushSharp#481]
Hi,

Anyone there to help in implementing broadcasting to APNS. I have around 80k users and I need to push a notification to all the users.
Is it a good way to split them in to chunks of 1000 and open a connection to APNS push 1000 and close connection on multiple threads? 
Pls suggest.
@Redth, pls help me to understand the better approach for performance.
Thanks.

**Comment by sasirekhak** [comment]
To be clear, I will create a thread for each 1000 devices, open a connection to APNS, queue 1000 devices, push and then Push.stopallservices(true). 
Is it a good approach?

**Comment by sasirekhak** [comment]
To be clear, I will create a thread for each 1000 devices, open a connection to APNS, queue 1000 devices, push and then Push.stopallservices(true). 
Is it a good approach?

**Comment by jesuslg123** [comment]
I don't know exactly about using this library, but you can create many connection too APNS as your net and machine can handle, apple won't reject, it's a good practice.
