### ISSUE TITLE
Custom sound for Windows Phone Toast notifications

### ISSUE THREAD

**Issue by bvnierop** [Redth/PushSharp#483]
Since Windows Phone 8 Update 3, there is the option to add a tag for a custom sound file to be played when a Toast is received. This would be done by using the `<wp:Sound/>` tag in the payload ([Source][1]).

From what I can gather, it is not possible to add this with PushSharp as it currently stands.

Since I need this for a project I am currently working on, that already succesfully uses PushSharp for the other platforms, I would be willing to add this feature.

  [1]: http://msdn.microsoft.com/en-us/library/windows/apps/jj662938%28v=vs.105%29.aspx#BKMK_gdr3

**Comment by roeaharoni365** [comment]
Hi, i'm joining on this request as well

btw - it could have been quite easy for expension if only ToastAudio.GenerateXmlElement() was virtual
i've intended to inherit ToastAudio and create CustomToastAudio that adds the option to set a custom audio without a need to change the pushsharp package

**Comment by lecamarade** [comment]
Why is it closed? Is there a way to do send a toast with custom sound?
