### ISSUE TITLE
Example of full implementation with feedback service?

### ISSUE THREAD

**Issue by neal007** [Redth/PushSharp#491]
Hello,

Right now I'm just setting up for Apple push notifications.  Does anyone have a full working sample putting all of the pieces together that show both sending X number of notifications and also handling the feedback service?

Thank you

**Comment by embassem** [comment]
you can follow this tutorial 
http://www.codeproject.com/Tips/666989/Using-PushSharp-to-Send-Notifications-to-iOS-and-A
but for   the number of notification you had to save it in database for each device and had a API point to reset the counter when user see them
