### ISSUE TITLE
Pushsharp doesn't send notification when the code is in a hosting

### ISSUE THREAD

**Issue by javiercabanillas** [Redth/PushSharp#493]
Hi,
I am trying to send notifications to android devices using PushSharp, when I use this library from my development environment works fine, but when I deploy the funcionality to my hosting (hostgator.com) doesn't send the notification to the device, and the code doesn't send any error.

Is there any issue or special configuration for a hosting/production environment?

I tried to send notifications using "the classic" way throw a httprequest using plain text (not json) and it works fine in my hosting, so maybe the error is the json format with the sender id (project number).

Can you help me please?

Thank you, greetings from Peru.

**Comment by r-abdelhamed** [comment]
I have the same problem 
can you help us please ?

**Comment by javiercabanillas** [comment]
I did not manage to make it work, I don't know what is the problem, I tried using the "classic way" to send notifications using JSon and the post method of google, and It works on my hosting. Maybe it is an error with PushSharp, I don't know.

You can find how to send notifications with Json and works fine in production environment here:
http://stackoverflow.com/questions/18508674/gcm-using-json-to-send-to-multiple-registrationids-no-notification-arrives

I review the code of PushSharp and extracted the part of handle events, so I reuse this part.

**Comment by r-abdelhamed** [comment]
Dear javiercabanillas,
Thanks a lot for your reply 
but i use PushSharp in WCF service it work well  in my  development machine but when i host wcf service on production server it send 
"The response status was 0.
Check out the W3C XMLHttpRequest Level 2 spec for more details about when this happens"

**Comment by asaturg** [comment]
Have you solved this issue? I have same problem , it's working fine on development machine but on hosting it's not sending notifications 

only OnChannelCreated is firing

**Comment by lukefan6** [comment]
Is it possible that the production environment has blocked the ip/port that APN/GCM are using?

**Comment by asaturg** [comment]
No all required ports are open, I've tested it using simple code to send APNS
