### ISSUE TITLE
can't use pushsharp on shared hosting

### ISSUE THREAD

**Issue by embassem** [Redth/PushSharp#494]
i get an execption when use pushsharp on shared hosting due to  trust level medium 

Request for the permission of type 'System.Security.Permissions.KeyContainerPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.

**Comment by sumedhmeshram** [comment]
I have a same issues. I am using godaddy shared hosting for sending push notificaiton and it is not working.
Please help

**Comment by asaturg** [comment]
Have you solved this issue? I have same problem , it's working fine on development machine but on hosting it's not sending notifications 

only OnChannelCreated is firing
