### ISSUE TITLE
% symbol does not go in APNS push notification

### ISSUE THREAD

**Issue by sasirekhak** [Redth/PushSharp#498]
Hi,

I have a payload which has % symbol and I notice that the push which I receive does not have the % symbol. 
If I insert an additional %, like %% then I receive % in my push

Example:
Payload: 50% off
Push I receive: 50 off

Payload: 50%% off
Push I receive: 50% off

Any idea how is apns interpreting this symbol.

Thanks in advance.

**Comment by alaa9jo** [comment]
Strange,I sent many notifications that includes characters like `%` or `€` and APNs sent them fine,I didn't have to use `%%` at all

APNS interpret payload as `UTF8`,please check on method `ToByte()` in file `AppleNotification.cs`
