### ISSUE TITLE
Debugging on production server

### ISSUE THREAD

**Issue by johnrickman** [Redth/PushSharp#504]
Hello All:

I got this library working on my development server without much trouble, but now I pushed it to a production server and notifications don't get sent. What are some ways to debug where its failing? The certificates should be fine.

**Comment by johnrickman** [comment]
Support at its worst..

**Comment by Redth** [comment]
I have already apologized on my blog for letting this project go.  The best way to try and fix that is to clear out the old noise, so unfortunately this and many other issues have been closed.

If you are having problems on 3.x, please feel free to open a new issue, preferably with a lot more information than "it doesn't work" which would help to help me diagnose the issue.

Thanks.
