### ISSUE TITLE
One Pushbroker for One ApplePushChannel ? or Many ApplePushChannel ?

### ISSUE THREAD

**Issue by jeromeliger** [Redth/PushSharp#505]
First of all, thanks for your work on PushSharp, it's amazing... all my test-notifications on the 3 platform are passed ! Now it's time to production work...

I'm doing a Windows Service with a timer on my server, to send notifications every X minutes.
I'm starting my pushbroker on the service_start, like you recommand on another post...

But I have actualy multiple mobile applications on this same "WindowsPushService".
So, I got in my DB multiple "certificate.p12" (for Apple, but it's the same mechanism with WP...) relative to each application, and I want to send the good notification to the good application... with the good channel (and certificate).

So my question is : 
- Does I need to instanciate as many as PushBroker that I have Applications (on service_start) ? and if yes, can-I attach all the PushBrokers events, to the same method ? (DeviceSubscriptionChanged() for exemple)
- or can-I instantiate only one PushBroker, and change "on-the-fly" the good PushChannel (for the good application) ? In that case, will I receive all the "events" ? (I don't think so, but it will be easier to program ;-))

Keep in mind that I have multiple applications, and each application got 3 channels (WP, Android, iOS)

Thanks for your advices.
![db_schema](https://cloud.githubusercontent.com/assets/3584319/7042840/03eb0a6c-dde5-11e4-8d44-684a0252339e.png)

Jérôme

**Comment by jeromeliger** [comment]
I'm gona answer to myself, it can be helpfull for other pushsharpers...

So the response is : implement as many as pushbroker that you have applications !

some tricks :

```C#

private static Dictionary<PushBroker, string> ListPushBroker

```

on service start :

```C#

ListPushBroker = new Dictionary<PushBroker, string>();
DataTable DT = DB_NotifyServer.GetAllApplication();
foreach (DataRow DR in DT.Rows)
{
    //Create our push services broker
    PushBroker CurrentPushBroker = new PushBroker();
    //Wire up the events for all the services that the broker registers
    CurrentPushBroker.OnNotificationSent += NotificationSent;
    CurrentPushBroker.OnNotificationRequeue += NotificationRequeued;
    CurrentPushBroker.OnNotificationFailed += NotificationFailed;
    CurrentPushBroker.OnDeviceSubscriptionExpired += DeviceSubscriptionExpired;
    CurrentPushBroker.OnDeviceSubscriptionChanged += DeviceSubscriptionChanged;
    CurrentPushBroker.OnChannelCreated += ChannelCreated;
    CurrentPushBroker.OnChannelDestroyed += ChannelDestroyed;
    CurrentPushBroker.OnChannelException += ChannelException;
    CurrentPushBroker.OnServiceException += ServiceException;
    var appleCert = File.ReadAllBytes(DR["ios_certificate_filepath"].ToString());
    //Apple
    ApplePushChannelSettings hostPush_APNS_setting = new                      ApplePushChannelSettings(production, appleCert, DR["ios_certificate_pwd"].ToString());
    CurrentPushBroker.RegisterAppleService(hostPush_APNS_setting);
    //Idem WP
    [...]
    CurrentPushBroker.RegisterWindowsPhoneService(hostPush_WPNS_setting);
    //Idem Android
    [...]
    CurrentPushBroker.RegisterGcmService(hostPush_GCM_setting);
    //And we add the current pushbroker to the static dictionary
    ListPushBroker.Add(CurrentPushBroker, DR["application_URL"].ToString());
}

```

And on the timer tick, we send the android, iOS and WP notification, foreach application, with the good pushbroker...

For exemple, to find the good application/pushbroker/notifications (ex: android)

```C#

DataTable DT = DB_NotifyServer.GetAllApplication();
foreach (DataRow DR in DT.Rows)
{
    PushBroker tempPushBroker = ListPushBroker.First(x => x.Value ==     DR["application_URL"].ToString()).Key;
    if (tempPushBroker != null)
    {
        List<Notification> ListeNotif =         DB_NotifyServer.GetNotifications_ToSend_Android(DR["application_URL"].ToString());
        if (ListeNotif.Count > 0)
        {
            foreach (Notification Notif in ListeNotif)
            {
                tempPushBroker.QueueNotification(
                new GcmNotification()
                .ForDeviceRegistrationId(Notif.device_id)
                .WithJson(JsonConvert.SerializeObject(notifdata)));
            }
        }
    }
}

```

It's maybe not the best solution, but all I can say is : that works !

I Love PushSharp (and Xamarin :+1: )
:-D

**Comment by smurfpandey** [comment]
Have a look at this: https://github.com/Redth/PushSharp#how-do-i-support-multiple-applications-with-pushsharp

Instead of creating multiple pushboroker for apple push, you can create 1 broker and register multiple service, once for each of your app.

**Comment by jeromeliger** [comment]
Thanks, in fact I didn't see it... I'm blind sometimes ;-)
But I'm in V2.0.0, not in 2.1.2 (still Beta), and as my solution's working well, I keep it on my mind but I'm not going to change now...
