### ISSUE TITLE
OLD device token and certificate working perfect but new certificate and divice token .....IOS push notifation not working.

### ISSUE THREAD

**Issue by jainik87** [Redth/PushSharp#509]
Show error:

You have selected the Development/Sandbox (Not production) server, yet your Certificate does not appear to be the Development/Sandbox certificate!  Please check to ensure you have the correct certificate!

.............Please Give me any suggestion for the same..

Thanks

**Comment by mattio** [comment]
@jainik87 That error message sounds very specific. If you're certain you're using the development certificate, are you passing `false` as first parameter when you create the channel?

`var channel = new ApplePushChannelSettings(false, certificate, password);`

My understanding is that parameter tells the PushSharp code to use the Apple dev server. 

If the certificate is the development one and you are passing `false` to that constructor, posting the relevant parts of your code here may allow someone else to help you.
