### ISSUE TITLE
Apple notification error

### ISSUE THREAD

**Issue by hasmukhsavaliya004** [Redth/PushSharp#512]
I am using PushSharp C# library to send apple push notification and almost from last one month I am getting following error to send notification.

Everything is complete to send a notification but from last month I am getting error like following, so please help me to solve this issue, and if any body is having any Idea then please tell me what is problem for sending notification.

PushSharp.Apple.ApplePushService -> PushSharp.Core.MaxSendAttemptsReachedException: The maximum number of Send attempts to send the notification was reached! -> {"aps":{"alert":"Test message","badge":1,"sound":"sound.caf"},"Type":0,"UserId":0}

**Comment by Fleskarn** [comment]
I tried to manually install the certificates on my Windows-machine and after I did that, pushes seems to go out correctly. Can you try do that and see if helps?

**Comment by hasmukhsavaliya004** [comment]
Hello Fleskarn,

Thank you for the reply, actually I did it already but still I am not getting any notification on the IOS device.

One thing is that I want to confirm from you that are you sure you are getting the notification on the any IOS Device? and did you checked on phone that notification is seems to be received? because some time I see in the handler for notification class the program shows as that notification sent(notificationSent handler)  but in actual it doesn't seems to be received.

So please verify these things and tell me the status or reply me so I can go forward for this urgency.

Thanks again.

**Comment by Fleskarn** [comment]
Yes, I get notifications on my device/s.

Are you sure you're using the correct device tokens (development and distribution generates different tokens), and also, make sure you have notifications enabled for the app on the specific device you're trying to test on?

**Comment by hasmukhsavaliya004** [comment]
Thanks for your reply Fleskarn,

I am trying to send notification from last one month but not able to send.

I thinks that may be issue in code, would you like to suggest me that usefull url to download that library for push notification please?

Thanks,
Hasmukh
