### ISSUE TITLE
Problems sending Apple Pushes

### ISSUE THREAD

**Issue by Fleskarn** [Redth/PushSharp#513]
Hello!

I have been following this guide 
http://www.raywenderlich.com/32960/apple-push-notification-services-in-ios-6-tutorial-part-1

to setup the Simple Push script and I have it working correctly. I would like to use Push Sharp though for a more solid implementation.. Using the same certificate and device Token, Push Sharp fails to deliver.. Worth mentioning is I have had Push Sharp working _sometimes_..

I have double and tripple checked I am using the same development certificate, token in both my php-script and the Push Sharp code, but Push Sharp doesn't deliver. Has anything changed to the APNS server recently?

This is the simple code I run.. (my cert is exported without a password)
PushBrokerApple testbroker = new PushBrokerApple("my_dev_cert.p12");
testbroker.SendNotification(token, message);

**Comment by ilyabreev** [comment]
Did you try to use last version of PushSharp? In my case all notifications delivered perfectly.
