### ISSUE TITLE
ApplePushChannel not connecting or sending.

### ISSUE THREAD

**Issue by ToastedJelly** [Redth/PushSharp#515]
I'm trying to upgrade from APNS-Sharp 1.0.4.4 and I'm using the current NuGet Version 2.2.1.0

After registering all events, the channel and sending a notification, nothing happens. No event fires, even if I wait for minutes. A test with GCM two weeks ago worked, just the Apple part seems to not work.

code shortened:
```
            push = new PushBroker();
            push.OnServiceException += push_OnServiceException;
            // shortened.. all On* events registered here.
            push.OnDeviceSubscriptionExpired += push_OnDeviceSubscriptionExpired;

            push.RegisterAppleService(
                new ApplePushChannelSettings(
                    config.Production,
                    config.Certificate,
                    config.CertPassword
                )
            );
...
            AppleNotification anot = new AppleNotification()
                .ForDeviceToken(token)
                .WithTag(id);
            if (alert != null) anot.WithAlert(alert);
            if (sound != null) anot.WithSound(sound);
            if (badge.HasValue) anot.WithBadge(badge.Value);
            if (custom != null) anot.WithCustomItem("cc", new object[1] { custom });
            notification = anot;
            push.QueueNotification(anot);
...
            Console.WriteLine("Press ENTER to stop server");
            Console.ReadLine();
...
            push.StopAllServices(true);
```
All the events write to a log if they're called, but none is called.

The Certificate works - I'm getting an error if I test it with the wrong password, none with the right.

If I try to send the same test Notification with APNS-Sharp and he same certificate/token, I receive it  on the phone.

Any Ideas?

**Comment by Fleskarn** [comment]
I tried to manually install the certificates on my Windows-machine and after I did that, pushes seems to go out correctly. Can you try do that and see if helps?

**Comment by ToastedJelly** [comment]
@Fleskarn Thank you, I can't remember if I had to do that on the machine that is running APNS-Sharp, but I tried  installing the certificates on the dev machine here and it didn't help. I also tried executing the code on the server that still runs APNS-Sharp and sends out push messages currently and the code showed the same problem there.
Any other ideas?

**Comment by ilyabreev** [comment]
Code looks fine. Are you using actual device tokens?
