### ISSUE TITLE
APNS Alert Title added iOS 8.2

### ISSUE THREAD

**Issue by bvgwi** [Redth/PushSharp#520]
Is there a way we may add the latest child properties for APNS alert payload?  These are new since iOS 8.2

title
title-loc-key
title-loc-args

https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html

Thank you.

**Comment by chrisnowak** [comment]
Have also been wondering about this - is there any plan or workaround for getting title to work?

**Comment by gazibilisim** [comment]
Hello;
Is there any plan or workaround for getting title to work?

thanks

**Comment by MobileMon** [comment]
Did anybody implement this for v2? I'm still using v2 and don't plan on changing any time soon
