### ISSUE TITLE
PushBroker extension methods depend on the concrete class instead of the interface (IPushBroker)

### ISSUE THREAD

**Issue by julealgon** [Redth/PushSharp#521]
Some time ago, an interface was extracted from the PushBroker class (https://github.com/Redth/PushSharp/commit/e718dab8804aaba527202caa1e28109f0e5c5acf), but extension methods present in the specific assemblies for registering services and such are still relying on the concrete implementation.

Up to now we were using our own interface and wrapper class to make unit testing possible. As soon as I saw that the IPushBroker interface was introduced, I proceeded to delete our workaround wrappers and immediately noticed that code that wasn't supposed to break broke. It was because we were calling some of those extension methods like 'RegisterGcmService' or 'RegisterAppleService'.

Please change those extension methods to work on the interface directly instead of the concrete implementation. The extension methods do not need anything that is only present in the concrete class.

**Comment by rupe120** [comment]
https://github.com/Redth/PushSharp/pull/597
