### ISSUE TITLE
.pem certificate instead of .p12?

### ISSUE THREAD

**Issue by mobedi** [Redth/PushSharp#523]
I would like to send a test PUSH message to an iOS device. I am provided with the device token and one `.pem` file as certificate. But I cannot seem to find a way to create a new `ApplePushChannelSettings` object using this `.pem` file. The examples on the git README all uses a `.p12` file that come with a password.

    //Create our push services broker
    var push = new PushBroker();
    
    //Registering the Apple Service and sending an iOS Notification
    var appleCert = File.ReadAllBytes("ApnsSandboxCert.p12"));
    push.RegisterAppleService(new ApplePushChannelSettings(appleCert, "pwd"));
    push.QueueNotification(new AppleNotification()
                               .ForDeviceToken("DEVICE TOKEN HERE")
                               .WithAlert("Hello World!")
                               .WithBadge(7)
                               .WithSound("sound.caf"));

Should I ask for a `.p12` certificate for the target app or is there a way to use a `.pem` file with *PushSharp*?

Thanks in advance!

**Comment by StephenStrickland** [comment]
@mobedi To the best of my knowledge, you need a .p12 file.

**Comment by luiscarlostic** [comment]
.pem file is for Apache servers
