### ISSUE TITLE
While queueing notifications nothing happens at all

### ISSUE THREAD

**Issue by ilyabreev** [Redth/PushSharp#525]
```c#
    public class Push
    {
        private readonly PushBroker _push;

        private static Push _instance;

        public static Push Instance
        {
            get { return _instance ?? (_instance = new Push()); }
        }

        public Push()
        {
            _push = new PushBroker();
            _push.OnNotificationSent += new NotificationSentDelegate(_push_OnNotificationSent);
            _push.OnNotificationFailed += new NotificationFailedDelegate(_push_OnNotificationFailed);
            _push.OnServiceException += new ServiceExceptionDelegate(_push_OnServiceException);
            _push.OnChannelCreated += new ChannelCreatedDelegate(_push_OnChannelCreated);
            _push.OnChannelDestroyed += new ChannelDestroyedDelegate(_push_OnChannelDestroyed);
            _push.OnChannelException += new ChannelExceptionDelegate(_push_OnChannelException);
            _push.OnNotificationRequeue += new NotificationRequeueDelegate(_push_OnNotificationRequeue);
            _push.RegisterAppleService(new ApplePushChannelSettings(false, File.ReadAllBytes(@"C:\PathToCertificate\Name.p12"), "***"), "myAppId", new PushServiceSettings()
            {
                Channels = 1,
                AutoScaleChannels = false
            });
        }

        void _push_OnNotificationRequeue(object sender, NotificationRequeueEventArgs e)
        {
            Debug.Print("requeue");
        }

        void _push_OnChannelException(object sender, IPushChannel pushChannel, Exception error)
        {
            Debug.Print("channel exception");
        }

        void _push_OnChannelDestroyed(object sender)
        {
            Debug.Print("channel destroyed");
        }

        void _push_OnChannelCreated(object sender, IPushChannel pushChannel)
        {
            Debug.Print("channel created");
        }

        void _push_OnServiceException(object sender, System.Exception error)
        {
            Debug.Print("service exception");
        }

        void _push_OnNotificationFailed(object sender, INotification notification, System.Exception error)
        {
            Debug.Print("failed");
        }

        void _push_OnNotificationSent(object sender, INotification notification)
        {
            Debug.Print("sent");
        }

        public void Send(Notification notification)
        {
            _push.QueueNotification(notification);
            _push.StopAllServices("biz.sintek.Rotapost", true);
        }

        public void SendAppleNotification(string deviceToken, string text)
        {
            Send(new AppleNotification()
                .ForDeviceToken(deviceToken)
                .WithAlert(text)
                .WithSound("default"));
        }
    }
```

no events called, no exceptions throwed, no notifications sent.

**Comment by ilyabreev** [comment]
Problem was in my `Send` method. `QueueNotification` is generic and defines type of notification at compile time. If I calling `QueueNotification` with `new AppleNotification()` it works like a charm!

**Comment by sbaker** [comment]
i ran in to this problem as well. When I abstracted away the type of notification, the call to QueueNotification<TNotification>(TNotification notification) broke. My suggestion is to register based off notification.GetType() which will always return the type where typeof(TNotification) may not always send the notification to the proper channel.

But thanks for creating the framework and tackling the challenge! Great work!

**Comment by sbaker** [comment]
Here was my solution.

	public class DefaultPushService : PushService
	{
		private static readonly PushBroker Broker = new PushBroker();

		public override void Initialize(string gcmAuthToken, X509Certificate2 apnsCertificate)
		{
			Broker.OnNotificationFailed += BrokerNotificationFailed;
			Broker.OnNotificationSent += BrokerNotificationSent;
			Broker.OnChannelException += BrokerChannelException;
			Broker.OnServiceException += BrokerServiceException;
			var settings = new PushServiceSettings { Channels = 10 };
			Broker.RegisterGcmService(new GcmPushChannelSettings(gcmAuthToken), settings);
			Broker.RegisterAppleService(new ApplePushChannelSettings(apnsCertificate), settings);
		}

		private static void BrokerServiceException(object sender, Exception error)
		{
			
		}

		private static void BrokerChannelException(object sender, IPushChannel pushChannel, Exception error)
		{
			
		}

		private static void BrokerNotificationSent(object sender, INotification notification)
		{
			
		}

		private static void BrokerNotificationFailed(object sender, INotification notification, Exception error)
		{

		}

		public override void Send(IPushContext context)
		{
			if (context == null) { return; }

			var notification = context.CreateNotification();

			if (notification == null) { return; }

			notification.Tag = context;

			Broker.Send(notification);
		}

		protected override void Dispose(bool disposing)
		{
			Broker.StopAllServices();
		}
	}

	internal static class PushBrokerExtensions
	{
		public static void Send(this IPushBroker broker, INotification notification)
		{
			var appleNotification = notification as AppleNotification;

			if (appleNotification != null)
			{
				broker.QueueNotification(appleNotification);
				return;
			}

			var androidNotification = notification as GcmNotification;

			if (androidNotification != null)
			{
				broker.QueueNotification((GcmNotification)notification);
			}
		}
	}
