### ISSUE TITLE
Apple Push Notifications are sometimes not delivered

### ISSUE THREAD

**Issue by mariorasch** [Redth/PushSharp#529]
Hi,

basically, I successfully set up PushSharp to deliver Push Notifications to Android (GCM), iOS (APNS production environment) and Windows Phone devices.

I activated debug logging and while PushSharp is running, many messages like this are logged (what I think says that PushSharp is running O.K.):

PushSharp.Android.GcmPushService -> Checking Scale (0 Channels Currently)
PushSharp.Apple.ApplePushService -> Checking Scale (1 Channels Currently)
PushSharp.WindowsPhone.WindowsPhonePushService -> Checking Scale (0 Channels Currently)

PushSharp.Android.GcmPushService -> Avg Queue Wait Time 0 ms, Avg Send Time 0 ms
PushSharp.Apple.ApplePushService -> Avg Queue Wait Time 0 ms, Avg Send Time 0 ms
PushSharp.WindowsPhone.WindowsPhonePushService -> Avg Queue Wait Time 0 ms, Avg Send Time 0 ms

Problem is: every once in a while push notifications successfully enqueued using PushBroker.QueueNotification will not being handled, i.e. no OnDeviceSubscriptionChanged, OnDeviceSubscriptionExpired, OnNotificationFailed, OnNotificationRequeue, OnNotificationSent or OnNotificationRequeue events are triggered.

Instead, e.g. with one Apple push notification that has been enqueued, at some point the following log entries show up:

PushSharp.Apple.ApplePushService -> Service Idle, Destroying all Channels
ApplePushChannel->Waiting...
ApplePushChannel: Cleaned up 1, Reconnects: 1
ApplePushChannel->DISPOSE.

So my question is: is there anything I have to do (like changing PushSharp settings or whatever) so that PushSharp *reliably* delivers push notifications *or* in case of any problem logs appropriate information?

Many thanks in advance & best regards!
Mario.

**Comment by mariorasch** [comment]
@Redth Hi Jonathan, it would be great if you could help with my question above? Do you have any hint for me why sometimes Apple push notifications do not get delivered and what I could do to fix this (e.g. changing channel settings)? Many thanks in advance!

**Comment by jastisatya** [comment]
we are facing the same issue sometimes APNS notifications are not getting delivered

**Comment by mariorasch** [comment]
Alas it seems we won't get any support from @Redth regarding this issue. As soon as I have some spare time from my other tasks and tickets I will have a look at the source code and hopefully will be able to optimize it.
