### ISSUE TITLE
apple push from hosted asp.net fails on obtaining permission KeyContainerPermission

### ISSUE THREAD

**Issue by bweeres** [Redth/PushSharp#53]
Request for the permission of type 'System.Security.Permissions.KeyContainerPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.

This works fine on my development machine but fails when I push to my shared host (hostgator). 
The call that is failing on is 
new X509Certificate2(certificateData, certificateFilePwd,
                X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.Exportable)

I understand why it is failing but not sure what to do about it. I am surprised no one else has encountered this.

**Comment by skaseemuddin** [comment]
i got it working on hostgator too with the following changes.

X509Certificate2 certificate = new X509Certificate2(appleCert, "123456", 
                            X509KeyStorageFlags.MachineKeySet );



                        var config = new ApnsConfiguration(ApnsConfiguration.ApnsServerEnvironment.Sandbox,
                           certificate, false);
