### ISSUE TITLE
Clear Notification Badge in pushsharp

### ISSUE THREAD

**Issue by lordbyronxxiv** [Redth/PushSharp#531]
We are using PushSharp to send out notifications on our IOS App, but I am not sure how to tell the app to clear the notification badge to clear out once the user accesses the messages. Is this something that we have to get from apple? Here is the code that I am Using.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using PushSharp;
using PushSharp.Apple;
using System.Data.SqlClient;
using System.Data;

namespace swapaPushNotification
{
    class Program
    {
        static void Main(string[] args)
        {
            var pushBroker = new PushBroker();
            var cert = File.ReadAllBytes(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Certificates.p12"));
            var appleSettings = new ApplePushChannelSettings(true,cert, "-----");

            pushBroker.RegisterAppleService(appleSettings);
            
            SqlConnection con = new SqlConnection("Server=server");
            con.Open();
            SqlCommand storedProcConnect = new SqlCommand("stored procedure", con);
            DataSet storedProcDataset = new DataSet();
            SqlDataAdapter storedProcAdapter = new SqlDataAdapter(storedProcConnect);
            storedProcAdapter.Fill(storedProcDataset);
            if (storedProcDataset != null && storedProcDataset.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow row1 in storedProcDataset.Tables[0].Rows)
                {
                    string pilotid = row1["pilotid"].ToString();
                    string error = row1["error"].ToString();
                    SqlCommand selectDevID = new SqlCommand("Select TokenStr from dbo.Custom_PushToken where EmpID =" + pilotid, con);

                    DataSet DevIDDataset = new DataSet();

                    SqlDataAdapter pushTokenAdapter = new SqlDataAdapter(selectDevID);
                    pushTokenAdapter.Fill(DevIDDataset);

                    if (DevIDDataset != null && DevIDDataset.Tables[0].Rows.Count > 0)
                    {
                        foreach (DataRow row in DevIDDataset.Tables[0].Rows)
                        { 
                            string devid = row["TokenStr"].ToString();
                            var n = new AppleNotification()
                        .ForDeviceToken(devid).WithAlert(error).WithBadge(1).WithSound("Default");

                            pushBroker.QueueNotification(n);

                        }
                    }
                }
            }
            pushBroker.StopAllServices();            
            con.Close();
        }
    }
}
Any help is appreciated.
Mike

**Comment by ilyabreev** [comment]
I think that PushSharp is not responsible for clearing the badge out.
It just sends badge counter to APNS.

If you'd like to clear your application badge then you can do it inside your app.

in Obj-C:
```objc
[[UIApplication sharedApplication] setApplicationIconBadgeNumber:0];
```

in Swift:
```swift
UIApplication.sharedApplication().applicationIconBadgeNumber = 0
```
