### ISSUE TITLE
newtonsoft.json 7.01 problem

### ISSUE THREAD

**Issue by ezar** [Redth/PushSharp#532]
Good morning,
I upgraded json library in a project and when I try to use the pushsharp gives an error indicating that cannot find json 6.0 dll.
What's the problem?

**Comment by mattkhaw** [comment]
Just use the ver 6.0 DLL. This won't work with other version DLLs unless you re-compile yourself.

**Comment by Maximusya** [comment]
If you don't want to re-compile PushSharp projects to update their nuget json.net version, you may try binding redirection: [Redirecting Assembly Versions](https://msdn.microsoft.com/en-us/library/7wd6ex19(v=vs.110).aspx)

**Comment by kcd83** [comment]
;-)
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
...
  <runtime>
      </dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral"/>
				<bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="7.0.0.0"/>
			</dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```
