### ISSUE TITLE
Android notification

### ISSUE THREAD

**Issue by homerokzam** [Redth/PushSharp#533]
Does anyone have a recent example of how to send a notification to Android (asp.net)?

**Comment by rochabr** [comment]
I'd like one, too. Can't seem to get it to work.

**Comment by jamesdilcock** [comment]
The example in the sample project is wrong. It requires a "message" element otherwise they don't get received anywhere but when the app is in the foreground.

Like this

.WithJson("{\"alert\":\"Hello World!\",\"badge\":7,\"message\":\"test\"}"));

**Comment by homerokzam** [comment]
Thanks.
