### ISSUE TITLE
Is it still maintained ?

### ISSUE THREAD

**Issue by MisterJack49** [Redth/PushSharp#540]
Hi,

Is this project still maintained ? Do we have any news about the 3.x version ?

Regards

**Comment by profporridge** [comment]
Hasn't been much activity in the past 9 months or so

**Comment by Zapnologica** [comment]
Looks like an awesome project. I wander if its not maintained because it doesn't need any upgrades at this moment in time or if its been abandoned?

**Comment by makerofthings7** [comment]
The lead developer now works for Xamarin, and is swamped with other projects.

**Comment by Redth** [comment]
Yeah sorry folks, no time for this project lately.  I did start a rewrite of it (haven't released that code yet) and work on it here and there, but I don't see myself having a lot of time for it going foward, and given that Azure and Amazon both offer very comprehensive push notification services at really low prices, I think they are better options than rolling your own.

**Comment by biapar** [comment]
Azure free until a big number of subscriber...
