### ISSUE TITLE
Is Push Sharp Thread safe?

### ISSUE THREAD

**Issue by Zapnologica** [Redth/PushSharp#541]
I want to have several worker threads that all queue notifications to the PushBroker. What is the correct design to go about doing this? 

1: You have one instance of `PushBroker()` and then in each thread calls ` push.QueueNotification()` and the carries on with what it has to do. while the pushbroker handles the sending of the notification?

or

2: In each thread create an instance of PushBroker() , queue the notification, wait for it to send, and then dispose of the PushBroker instance?

Or maybe there is a better way which I have not thought of.

Thanks

**Comment by smurfpandey** [comment]
Use approach 1

If you create & dispose PushBroker, the connection will be opened & closed everytime. With single PushBroker, you can utilize the existing connection.

Also, apple doesn't like if you keep opening & closing connections multiple times.

**Comment by sharat** [comment]
Apple supports to have multiple `persistent connections` to APNS.

Based on the [documentation](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/CommunicatingWIthAPS.html)

> You may establish multiple connections to the same gateway or to multiple gateway instances. If you need to send a large number of remote notifications, spread them out over connections to several different gateways. This improves performance compared to using a single connection: it lets you send the remote notifications faster, and it lets APNs deliver them faster.

If you keep on open/close the connections, Apple will treat it as DDoS which could further reject your requests.
> Keep your connections with APNs open across multiple notifications; don’t repeatedly open and close connections. APNs treats rapid connection and disconnection as a denial-of-service attack. You should leave a connection open unless you know it will be idle for an extended period of time—for example, if you only send notifications to your users once a day it is ok to use a new connection each day.

**Comment by sasirekhak** [comment]
@Zapnologica, did you find a solution for you problem? I have the same issue.

**Comment by sasirekhak** [comment]
@Zapnologica, did you find a solution for you problem? I have the same issue.

**Comment by Zapnologica** [comment]
Thank you for all your responses.

@sasirekhak 

I have gone with a singleton instance of pushsharp, and each thread will then call `en-queue`. Once I have finished up with the code I will post it here.

**Comment by sasirekhak** [comment]
@Zapnologica, any luck?
