### ISSUE TITLE
Couldnt resolve 'the maximum number of send attempts to send the notification was reached' issue

### ISSUE THREAD

**Issue by sasirekhak** [Redth/PushSharp#545]
Hi, 
am using pushsharp library to send notifications to iOS devices. It was working fine quite for some time but suddenly am receiving 'the maximum number of send attempts to send the notification was reached' error.

I tried to update pushsharp libraries. Port 2195 is open in firewall.

Is there anything that I can try. Please help to resolve this.

Any help is appreciated.

Thanks in advance.

**Comment by u2194739** [comment]
This pushsharp library still works?

**Comment by b22n** [comment]
+1
