### ISSUE TITLE
Is live this project?

### ISSUE THREAD

**Issue by biapar** [Redth/PushSharp#552]
Is live this project?

**Comment by denstorti** [comment]
same question, still works though :)

**Comment by roman-yagodin** [comment]
:+1:

**Comment by roman-yagodin** [comment]
the same question also :+1:

**Comment by teopost** [comment]
Is dead !

**Comment by rrispoli** [comment]
Same question here... I'm planning to use this in a project, but I'm insecure because the last commit has 1 year.

Any other alternatives?

**Comment by Redth** [comment]
Hi folks, apologies for abandoning this project for some time, but I've finally had time to get back to it.  I'm working on a 3.0 version which is a complete rewrite using all the latest API's from the providers and better patterns.  I'm not planning on maintaining the 2.x versions, but you can try out the 3.0 branch already!  https://github.com/Redth/PushSharp/tree/3.0-dev
