### ISSUE TITLE
Pushsharp library creates millions of connection to 2196 port.

### ISSUE THREAD

**Issue by navjotsingh013** [Redth/PushSharp#556]
I am using pushsharp to send notification to both android and apple devices. I have configured window service with 1 minute interval. Notifications are sending successfully but after few days the connections to apple server with 2196 port reaches to 3.5 millions. When i restart the service all opened connections destroyed but again after week or so opened connections reach to millions. I have made changes to code but didn't work.

ApplePushChannelSettings settings = new ApplePushChannelSettings(production, appleCert, p12FilePassword);

                    PushServiceSettings pss = new PushServiceSettings() { AutoScaleChannels = false, Channels = 1, MaxAutoScaleChannels = 1 };

It might be related to feedback service. I don't know how to acknowledge or kill feedback connections. I am doing nothing in pushsharp events.

static void DeviceSubscriptionChanged(object sender, string oldSubscriptionId, string newSubscriptionId, INotification notification)
        {
           
        }

        static void NotificationSent(object sender, INotification notification)
        {

        }

        static void NotificationFailed(object sender, INotification notification, Exception notificationFailureException)
        {

        }

        static void ChannelException(object sender, IPushChannel channel, Exception exception)
        {
        }

        static void ServiceException(object sender, Exception exception)
        {
        }

        static void DeviceSubscriptionExpired(object sender, string expiredDeviceSubscriptionId, DateTime timestamp, INotification notification)
        {
        }

        static void ChannelDestroyed(object sender)
        {
            WriteTextLog_ChannelDestroyed("");
        }

        static void ChannelCreated(object sender, IPushChannel pushChannel)
        {
            WriteTextLog_ChannelCreated("");
        }

**Comment by walkerwzy** [comment]
I came across the same issue, but it's connect to 2195, 7k/minus
