### ISSUE TITLE
Http/2 New Provider API

### ISSUE THREAD

**Issue by gabrieligbastos** [Redth/PushSharp#557]
Hey,

I know it is a contribution repository. Maybe I will get some time to learn and study and help to implement in the end of the year but I would like to know if there is any estimated date for implementation of those new features with PushSharp?

https://developer.apple.com/videos/wwdc/2015/?id=720

Thanks in regards,

**Comment by Redth** [comment]
@gabrieligbastos the PushSharp 3.x versions will support this once Apple releases some specs on the implementation.  The video shows some basics, but currently Apple has not released anything more official than what's in the video.

Thanks!
