### ISSUE TITLE
NotificationFailed error

### ISSUE THREAD

**Issue by mer-lion** [Redth/PushSharp#559]
Hi, 
This is my test to send push Notification the problem is that in the QueueNotification method an error appears See the image.
![e](https://cloud.githubusercontent.com/assets/14870534/10133009/d3c62502-65e2-11e5-8764-801b0934c181.png)

**Comment by itonyday** [comment]
at first, it works, but now it does not work, i have changed nothing, it is just....something wrong....i dont know why.

**Comment by itonyday** [comment]
![image](https://cloud.githubusercontent.com/assets/13461924/10724602/c9092716-7c00-11e5-8456-848cc9ad567e.png)
