### ISSUE TITLE
StopAllServices() hangs and never stopped working.

### ISSUE THREAD

**Issue by nevraydin** [Redth/PushSharp#561]
Hi, I'm using PushSharp 2.1.2 and I have a common problem. After push notifications and all kind of works, StopAllServices() never kills and continues to work. As some comments said, I try to compare to device types and I see that problem for only iOS. 

Any thoughts why does StopAllServices() continue to work? 

Thanks.

**Comment by tweek82** [comment]
Hi, see my response here: https://github.com/Redth/PushSharp/issues/562

It might be caused by trying to connect to the c2dm service.
