### ISSUE TITLE
SOLVED! C2DM Is shutdown -- StopAllServices(bool waitForQueuesToFinish = true) occasionally hangs since a few days

### ISSUE THREAD

**Issue by tweek82** [Redth/PushSharp#562]
Hi,

Since this Tuesday (20th October) the StopAllServices method on the PushBroker hangs a few times per day. I got Push Sharp running in a Windows Service. ~~It hangs always at the same point, after creating (extra) apple-Channels.~~ The latest calls are (from the Logs):

Sent: PushSharp.Apple.ApplePushService -> {"aps":{"alert" <..>
Sent: PushSharp.Apple.ApplePushService -> {"aps":{"alert" <..>
Sent: PushSharp.Apple.ApplePushService -> {"aps":{"alert" <..>
Sent: PushSharp.Apple.ApplePushService -> {"aps":{"alert" <..>
Sent: PushSharp.Apple.ApplePushService -> {"aps":{"alert" <..>
Sent: PushSharp.Apple.ApplePushService -> {"aps":{"alert" <..>
Channel Created for: PushSharp.Apple.ApplePushService
Channel Created for: PushSharp.Apple.ApplePushService
Channel Created for: PushSharp.Apple.ApplePushService
Sent: PushSharp.Apple.ApplePushService -> {"aps":{"alert" <..>
-- HANGS --

And no exception is thrown. Eventlogs don't show anything and TELNET to APNS works, or at least it works after I notice that the service hangs and log in to the machine.

Because I didn't do any updates or changes on the platform, I'm wondering if Apple APNS made some changes? Or perhaps they changed SSL/TLS requirements...

I hope some one can give me a clue.

Many thanks in advance!

**Comment by tweek82** [comment]
I've found this table of fault codes. I don't see any of these codes back in the logging, but I'm going to investigate if one of these points causes PushSharp to hang:
https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/CommunicatingWIthAPS.html#//apple_ref/doc/uid/TP40008194-CH101-SW12

**Comment by tweek82** [comment]
Hi all,

I discovered the Log feature of PushSharp... a bit late. And there I saw that the pushbroker is constantly trying to connect to the C2DM service... this service is offline since october 20th:

https://developers.google.com/android/c2dm/

**Comment by Maximusya** [comment]
Initially the issue was all about ApplePushService - and suddenly is renamed with the mention of Google's long deprecated C2DM.
Anyways nice it's solved by now

**Comment by tweek82** [comment]
Yeah I know... but I was staring at just 1 log file and that one stopped after Apple notifications. Only when I looked in to the PushSharp source code and discovered how the PushSharp-logger worked, I got the clue :)

**Comment by tweek82** [comment]
By the way, we all knew C2DM is deprecated. But what we didn't know is that it would be shutdown at a certain point ...and causing PushSharp to loop on c2dm authentication...

**Comment by Redth** [comment]
I didn't realize Google had shut down C2DM either, thanks for posting this!
