### ISSUE TITLE
Android Push not shoing in device but no error appears

### ISSUE THREAD

**Issue by evagelos21** [Redth/PushSharp#569]
Hi to all,
I am trying to send push to android device .
For IOS everything seems ok and the message appears in the phone.
My code for IOS:
var appleCert = File.ReadAllBytes(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Certificates.p12"));
push.RegisterAppleService(new ApplePushChannelSettings(false, appleCert, "12345")); //Extension method
push.QueueNotification(new AppleNotification()		
		.ForDeviceToken("mytokenid")
		.WithAlert("Hello World1!")
		.WithBadge(1)
		.WithSound("default")
		);
push.StopAllServices();

For Android although NO error message appears and the "OnNotificationSent" event fires , in my Mobile nothing happens
my code for android:
push.RegisterGcmService(new GcmPushChannelSettings("MyApiKey"));
push.QueueNotification(new GcmNotification().ForDeviceRegistrationId("MyDevReg")
					  .WithJson("{\"alert\":\"Hello World!\",\"badge\":1,\"sound\":\"sound.caf\"}"));
push.StopAllServices();

any ideas why not or what I must check?

For Andoid is possible to have the badge auto-increment?

Thanks in advance

**Comment by Redth** [comment]
Android does not automatically do alerts for you.  You must handle the payload data yourself and write your own code to display a notification and make a sound (and Android doesn't support badges - not in AOSP anyway).

**Comment by evagelos21** [comment]
I cannot understand your replay.
This means that PushSharp cannot send Push to any Android device? and I must write extra program to handle the push messages?!!!

**Comment by alaa9jo** [comment]
Android is different from iOS regarding showing notifications,on iOS the system handles showing notifications automatically,however on android your have to write your own code on android application to catch the notification once received from the server and show it on the system

Here is a [link to a sample](https://github.com/googlesamples/google-services/blob/master/android/gcm/app/src/main/java/gcm/play/android/samples/com/gcmquickstart/MyGcmListenerService.java) from Google on how to handle notifications on android
