### ISSUE TITLE
Question: About StopBroker() when parallel sending notification

### ISSUE THREAD

**Issue by jimior2** [Redth/PushSharp#575]
My question is if the service have triggered from multiple and parallel the service do we need to StopBroker() in every calling from client or just leave it there no need to StopBroker() ?

**Comment by khanhvu161188** [comment]
@jimior2 i tried to stop and start again and it gave me error. so i decide to keep it always start without stop. And it still work normally here

**Comment by jimior2** [comment]
@khanhvu161188 Thanks, that's a good idea, I'm thinking the same here.
