### ISSUE TITLE
PayLoad is null in Android devices.

### ISSUE THREAD

**Issue by subramanyaYash** [Redth/PushSharp#577]
Hello All,

I am using this code to send the notification to Android devices. 

 push.RegisterGcmService(new GcmPushChannelSettings("MY Sender ID", "App Key", "App ID"));
            push.QueueNotification(new GcmNotification().ForDeviceRegistrationId("device Token ID")
                                  .WithJson("{\"alert\":\"Hello World Android!\",\"badge\":1,\"sound\":\"sound.caf\"}"));

But on the device i am getting error which says "payload is null". Below is my code on Android devices. I am using Appcelerator to build the app.
CloudPush.addEventListener('callback', function(e) {
		alert(e);
		var andpayload = JSON.parse(e.payload);
		Ti.UI.createAlertDialog({
			message : andpayload.android.alert,
			ok : 'Ok',
			title : andpayload.android.title
		}).show();
	});

Can anyone please help on this.

Regards,
Subramanya

**Comment by subramanyaYash** [comment]
Can anyone please help me on this. Its very urgent. As the app is waiting for the store upload. Only because of this we are not able to publish to stores from last 1 week.

**Comment by Redth** [comment]
Try making the badge value a string with quotes.  Google doesn't really allow true JSON unfortunately, it's just key/value string pairs.
