### ISSUE TITLE
PushSharp Apple Push notification Issue 

### ISSUE THREAD

**Issue by ankur-4-garg** [Redth/PushSharp#587]
Hi, 

I am using PushSharp in my project and now I am facing strange problem. When I send push to iOS device, I do get callback for ChannelCreated however after that nothing happens. I neither receive any error NOR success for notification sent. Hope you can suggest a solution for this.

**Comment by erick2red** [comment]
**+1**

**Comment by mpitot** [comment]
+1

**Comment by denstorti** [comment]
Are you registering Apple service without any problem? Is it calling DoChannelWork of PushServiceBase?

**Comment by CoBoltDK** [comment]
Have you tried looking at this?

**Comment by mpitot** [comment]
Hello,
I used ApnsServiceBroker without problems! I couldn't tell you if it's
calling DoChannelWork of PushServiceBase sorry :/

2016-01-28 10:20 GMT+01:00 Dennis Jørgensen <notifications@github.com>:

> Have you tried looking at this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Redth/PushSharp/issues/587#issuecomment-176078177>.
>



-- 
Cordialement,

Maxime PITOT
Owner, *NUBYtouch*
nubytouch.com
<http://nubytouch.com>
+33 1 45 57 03 88
+33 6 72 32 88 70
