### ISSUE TITLE
APNS Certificate issue in Prodcution 

### ISSUE THREAD

**Issue by perlasivakrishna** [Redth/PushSharp#588]
I Used push sharp for all of my applications, All are working fine except the recent one. 
Im getting Following error Even though i selected production certificate..
You have selected the Production server, yet your Certificate does not appear to be the Production certificate! Please check to ensure you have the correct certificate!

What are the possible reasons for this ?

**Comment by harshadcs** [comment]
Same error :
Additional information: You have selected the Production server, yet your Certificate does not appear to be the Production certificate!  Please check to ensure you have the correct certificate!

**Comment by v-tsymbalistyi** [comment]
New Apple push production certificate format. #586

**Comment by harshadcs** [comment]
@v-tsymbalistyi  I already tried this example. above error have been fixed but push notification is not working in apple production service certificate.

**Comment by trevoriancox** [comment]
Works for me. Suggest closing this as duplicate.

**Comment by perlasivakrishna** [comment]
@trevoriancox, Could U please help me, We are unable to change/edit disablecertificatecheck to true in ApplePushChannelSettings class.. How can I make them editable....

Thanks..

**Comment by hemang-azilen** [comment]
@v-tsymbalistyi , Is this issue solved? I'm an iOS developer and need to know our .Net developer to update your library on server. Thanks!

**Comment by Juliete** [comment]
For me don't work, when I send a notification a OnNotificationFailed is produced with the message "APNS NotificationFailureException -> 8: Invalid Token"

**Comment by hemang-azilen** [comment]
@Juliete , what changes you have done for this?

**Comment by Juliete** [comment]
In ApplePushChannelSettings.cs I change:
if (production && !subjectName.Contains("Apple Production IOS Push Services"))
to:
if (production && !subjectName.Contains("Apple Production IOS Push Services") && !subjectName.Contains("Apple Push Services"))

But this is the same that if you pass to true the parameter production to the constructor of the ApplePushChannelSettings class

**Comment by hemang-azilen** [comment]
@Juliete, Ok, I guess we should wait until an update will be release.

**Comment by Redth** [comment]
I won't be updating the 2.x version with changes, but the 3.0-dev branch already contains these changes.  If you want to keep using 2.x, you can just use the constructor for `ApplePushChannelSettings` that allows you to se the `production` and `disableCertificateCheck` flags accordingly, no need to recompile to work around this.

**Comment by perlasivakrishna** [comment]
Thank you so much, 
pushBroker.RegisterAppleService(new ApplePushChannelSettings(true, appleCertificate, password, true));
After this change every thing is working fine, Previously we are trying to edit in the class(ApplePushChannelSettings where There is a defined constructor with value False).

Thanks..

**Comment by rodneyworkman291** [comment]
That worked.  Thank you
