### ISSUE TITLE
Push Notification is not working after using new Apple push production.

### ISSUE THREAD

**Issue by harshadcs** [Redth/PushSharp#591]
Can you please confirm that Push Notification is working after new Apple push production.(P12 policy updated by iOS  https://developer.apple.com/news/?id=12172015b)?
We changed our code as per your new code, we are not getting any exception, but we are also not getting Notification.

**Comment by perlasivakrishna** [comment]
@harshadcs How u changed ur code, r u babe to edit the code, v are unable to edit the code please help me

**Comment by harshadcs** [comment]
@perlasivakrishna We changed our code as per PushSharp new code done in 3.0 dev branch. After that we are not getting any exception in backend side code, but we are also not getting Notifications.

**Comment by kmmastermind** [comment]
@Redth Can you please help in resolving issue for Push Notification not getting send . Here is a link for certificate I am using and other information required are in zip file. It is a production certificate.

https://www.dropbox.com/s/rvvxmdeiq1l7htq/PushSharp.zip?dl=0

Thanks in advance.

**Comment by Redth** [comment]
Guys just use the ctor of the apns settings to disable the certificate check and explicitly set the production flag
