### ISSUE TITLE
Subject name production certificate

### ISSUE THREAD

**Issue by oystehei** [Redth/PushSharp#593]
Just updated my push certificates and began experiencing problems sending out notifications using the production certificate. Turns out Apple has changed the subject name for the production certificate from "Apple Production IOS Push Services" to simply "Apple Push Services". As a result the *CheckProductionCertificateMatching* in the *ApplePushChannelSettings* fails.

Solved it temporarily by using setting the *disableCertificateCheck* to true in the constructor.

**Comment by Redth** [comment]
Yep, this is fixed in the 3.0-dev branch (and 3.x nuget releases).  I will not be updating the legacy 2.x branches with a fix.
