### ISSUE TITLE
The New Certificate Connot RegisterAppleService 

### ISSUE THREAD

**Issue by gsj0791** [Redth/PushSharp#596]
ApplePushChannelSettings.cs line 90 need add
 if (subjectName.Contains("Apple Push Services"))
                    production = true;
and in the CheckProductionCertificateMatching function
if (production && !subjectName.Contains("Apple Production IOS Push Services")) 
change to
if (production && !subjectName.Contains("Apple Production IOS Push Services") && !subjectName.Contains("Apple Push Services"))

**Comment by Demivan** [comment]
I have same issue with 3.0
Development certificate subject contains: "Apple Development IOS Push Services" not "Apple Push Services"

**Comment by Redth** [comment]
I won't be updating the 2.x version with changes, but the 3.0-dev branch already contains these changes. If you want to keep using 2.x, you can just use the constructor for ApplePushChannelSettings that allows you to set the production and disableCertificateCheck flags accordingly, no need to recompile to work around this.

**Comment by khalidzaman** [comment]
Same issue at my side too (The New Certificate Connot RegisterAppleService) .
I have installed the latest version 2.2.1.0 of PushSharp from nuget packges,and created new production certificates few days ago. But my code is always throwing exception at RegisterAppleService (You have selected the Production server, yet your Certificate does not appear to be the Production certificate!  Please check to ensure you have the correct certificate). My old certificates which i have created for other projects few months ago are working fine with the same PushSharp version 2.2.1.0, also the same PushSharp version 2.2.1.0 is working fine with new Development Certificates.

I tried diffrent things but all in vain. Any help will be highly appreciatable.
Thanks

**Comment by Redth** [comment]
@khalidzaman i answered this already in the comment before you posted.  Here's a lengthier explanation as well: 
http://stackoverflow.com/questions/34856909/push-notification-using-c-sharp-push-sharp-library-is-not-working-on-production

**Comment by khalidzaman** [comment]
@Redth.Thanks man,let me try with 3.x version.

**Comment by khalidzaman** [comment]
PushSharp latest stable version is 2.2.1, so PushSharp 3.x didn't worked for me. This worked form me  by setting the disableCertificateCheck parameter to true in the ApplePushChannelSettings class constructor for the PushSharp 2.x.
