### ISSUE TITLE
APNS over HTTP/2 can't authenticate successfully

### ISSUE THREAD

**Issue by DanWright91** [Redth/PushSharp#600]
I've been testing the HTTP/2 APNS functionality in the 3.0-dev branch (3.0.0-beta63). When I send a regular APNS notification using a newly generated dual-use certificate, it is successfully delivered. However, when I attempt to use the same certificate for the new HTTP/2 endpoint, an IOException is thrown with the message "Authentication failed because the remote party has closed the transport stream".

I've also checked that the certificate is working and that the ports aren't being blocked on my network by using the OpenSSL test client per Apple's troubleshooting steps: `openssl s_client -connect api.development.push.apple.com:443 -cert YourSSLCertAndPrivateKey.pem -debug -showcerts -CAfile server-ca-cert.pem`

**Comment by Redth** [comment]
Sorry but HTTP/2 is not quite ready yet... See #603
