### ISSUE TITLE
Exception of "Authentication failed because the remote party has closed the transport stream."

### ISSUE THREAD

**Issue by jimior2** [Redth/PushSharp#603]
I try to use 3.0 http2 version on APNS, then I got the exception "Authentication failed because the remote party has closed the transport stream." 
Is it cert issue or I need to setup my windows 7 port to binding with the cert?

**Comment by rupe120** [comment]
I had the same problem, I don't think the HTTP2 functionality is really ready yet

**Comment by Redth** [comment]
Yeah there's some issues with HTTP/2 still.  It might boil down to the fact that SslStream can't support ALPN.  I'm looking at trying to use BouncyCastle to do the TLS connections but that's not working out well at the moment either.  Stay tuned.

**Comment by sanjay2tech** [comment]
Hi Redth, I have consumed PushSharp 4.x in .Net 4.5 project and using HTTP/2 to send notification. But getting failure in response. Could you please provide sample code to test HTTP/2 to send notification. Also, please update whether all the issues are resolved with HTTP/2.
