### ISSUE TITLE
Production certificates got error

### ISSUE THREAD

**Issue by Basek** [Redth/PushSharp#604]
I had new certificate and now have a problem. When I use certificate like dev all is ok, but when like production i got a error: "You have selected the Production server, yet your Certificate does not appear to be the Production certificate! Please check to ensure you have the correct certificate!". But apple changed dev/prod certificates to universal now. I use build 2.2.1.

**Comment by rupe120** [comment]
Are you using the new dual use cert?

![image](https://cloud.githubusercontent.com/assets/860348/12581604/c6a0c82e-c405-11e5-81f6-50365372437e.png)

**Comment by Redth** [comment]
There are numerous bugs answered about this already, please read them.

http://stackoverflow.com/questions/34856909/push-notification-using-c-sharp-push-sharp-library-is-not-working-on-production
