### ISSUE TITLE
ReceivedRemoteNotification for MainActivity

### ISSUE THREAD

**Issue by jesusgarza** [Redth/PushSharp#605]
I am using PushSharp 2.2.1 and it is working without problems. I integrated the code from PushSharp.Client on my Xamarin.Form project and I'm receiving notifications on iOS and Android. My doubt is if there is a way to implement in Android something similar to the ReceivedRemoteNotification event that exists in AppDelegate. I need to respond to the notification in Android, but I don't know how to get from  PushHandlerService.OnMessage to AppDelegate.

Thanks for the help!

**Comment by rupe120** [comment]
https://developer.xamarin.com/guides/cross-platform/application_fundamentals/notifications/android/remote_notifications_in_android/#Implement_a_GCM_Listener_Service

**Comment by jesusgarza** [comment]
Thank you for the reference Joshua. It seems very similar to PushSharp.ClientSample, which I used on my Android project:
https://github.com/Redth/PushSharp/blob/master/Client.Samples/PushSharp.ClientSample.MonoForAndroid/PushSharp.ClientSample.MonoForAndroid.Gcm/PushService.cs
My problem is when the app is on the background and I click on the Notification (inside the notification drawer). I want the app to recognize this and act accordingly.
Right now, the app tries to open again (but its already running on the background), so it goes through MainActivity.OnCreate. 
To avoid this I used LaunchMode = LaunchMode.SingleTop on the MainActivity.
Now I receive a call to MainActivity.OnNewIntent, but the intent its almost the same that I get when I click on the app icon to open it manually, only some flags change. 
So I suspect that I have to adjust the creation of the notification to include something in the SetContentIntent parameter. But I am not sure. Hope that I'm being clear. Do you have any ideas?

Thanks again.

**Comment by rupe120** [comment]
You can control the way the app launches with the pending intent

https://developer.xamarin.com/guides/cross-platform/application_fundamentals/notifications/android/local_notifications_in_android/#Starting_an_Activity_from_a_Notification

**Comment by jesusgarza** [comment]
Great! so it is the intent that goes in the SetContentIntent of the Notification.Builder. I just have to work out the correct configuration so that the MainActivity receives the right information.
Thanks Joshua

**Comment by rupe120** [comment]
You're welcome
