### ISSUE TITLE
PushSharp 3 is not strong signed.

### ISSUE THREAD

**Issue by MosheL** [Redth/PushSharp#607]
I was forced to upgrade as PushSharp 2 do not recognize my new keys.

Trying to upgrade from 2.x to 3 on a test Windows Application - works.
Trying to use it on the main app - can't, becase of the DLLs is not strong typed.

trying to manually sign the keys - failed, as one DLL depend other one and NuGet is overwriting these files.

What I can do? It can be fixed on the main branch ?

thanks

**Comment by Redth** [comment]
I'd really prefer not to sign the assemblies, is there a particular reason you must use signed assemblies?

If I do decide to sign them I'll most likely include the .snk file and password for it right in the source project so folks don't have issues compiling from source.

**Comment by Redth** [comment]
Also, you can also pull the source, compile, and sign it yourself if you're really desperate :)

**Comment by Redth** [comment]
Furthermore, there's a pretty good explanation of why strong naming assemblies is probably not necessary: https://github.com/octokit/octokit.net/issues/405#issuecomment-41640976

**Comment by MosheL** [comment]
Hi !
1. Thanks
2. I need it because I am using DLL to DLL, so VS/IIS is forcing me to sign them.

**Comment by Redth** [comment]
You can also use ILRepack or https://github.com/brutaldev/StrongNameSigner to accomplish signing.

Can you elaborate on 2?  I'm not familiar with what 'DLL to DLL' means exactly.

**Comment by MosheL** [comment]
as I know, I cant  use non-signed DLL via other DLL on web project. I see a strange errors...

**Comment by MosheL** [comment]
Exception for example:

    "Could not load assembly. A strongly-named assembly is required." error even though assembly is strong named

**Comment by MosheL** [comment]
something strange.

I removed NuGet package and signed DLL.s

test application with nuget original - works.
with signed files I reciveing this exception (translated to JSON)

````
{"ClassName":"System.AggregateException",
"Message":"אירעה שגיאה אחת או יותר." // one or more errors
,"Data":{},"InnerException":{"NativeErrorCode":-2146893043
,"ClassName":"System.ComponentModel.Win32Exception","Message":"The credentials supplied to the package were not recognized","Data":{},"InnerException":null,"HelpURL":null,"StackTraceString":"   ב-  PushSharp.Apple.ApnsServiceConnection.<Send>d__2.MoveNext()","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nMoveNext\nPushSharp.Apple, Version=1.0.5858.36879, Culture=neutral, PublicKeyToken=bbebc209884a90f1\nPushSharp.Apple.ApnsServiceConnection+<Send>d__2\nVoid MoveNext()","HResult":-2147467259,
"Source":"PushSharp.Apple","WatsonBuckets":null},
"HResult":-2146233088,"Source":null,"WatsonBuckets":null,"InnerExceptions":[{"NativeErrorCode":-2146893043,"ClassName":"System.ComponentModel.Win32Exception","Message":"The credentials supplied to the package were not recognized","Data":{},"InnerException":null,"HelpURL":null,"StackTraceString":"   ב-  PushSharp.Apple.ApnsServiceConnection.<Send>d__2.MoveNext()","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nMoveNext\nPushSharp.Apple, Version=1.0.5858.36879, Culture=neutral, PublicKeyToken=bbebc209884a90f1\nPushSharp.Apple.ApnsServiceConnection+<Send>d__2\nVoid MoveNext()","HResult":-2147467259,"Source":"PushSharp.Apple","WatsonBuckets":null}]}
````

**Comment by Redth** [comment]
Not sure why strong namer isn't working for you, but I'm going to confirm I do not intend to sign PushSharp 3.
