### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by mahdi** [Redth/PushSharp#609]
I'm using V3.0 Beta 63 and faced an issue when I'm finished with adding all the tokens to broker queue.

In fact many notifications are sent but at a point I receive the following exception:
An existing connection was forcibly closed by the remote host
and then it stops sending more notifications from queue.

I guess this is related to those tokens who are not anymore valid on APNS servers and so APNS sends "Not Sent" response and it breaks the TCP connection.

Any idea on how to resolve this?

**Comment by Redth** [comment]
Try updating to the stable release, this should be fixed there :)
