### ISSUE TITLE
apns gets error in ApplePushChannelSettings . System.Security.Cryptography.CryptographicException

### ISSUE THREAD

**Issue by fssctb** [Redth/PushSharp#611]
System.Security.Cryptography.CryptographicException 未處理
  Message=參數錯誤。

  Source=mscorlib
  StackTrace:
       於 System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
       於 System.Security.Cryptography.X509Certificates.X509Utils._LoadCertFromBlob(Byte[] rawData, IntPtr password, UInt32 dwFlags, Boolean persistKeySet, SafeCertContextHandle& pCertCtx)
       於 System.Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromBlob(Byte[] rawData, Object password, X509KeyStorageFlags keyStorageFlags)
       於 System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
       於 System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
       於 PushSharp.Apple.ApplePushChannelSettings..ctor(Byte[] certificateData, String certificateFilePwd, Boolean disableCertificateCheck)
       於 ConsoleApplication1.Program.Main(String[] args) 於 D:\Users\rueishiang.fan\documents\visual studio 2010\Projects\ConsoleApplication1\ConsoleApplication1\Program.cs: 行 22
       於 System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       於 System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       於 Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       於 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
       於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       於 System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by Redth** [comment]
Sorry but I cannot read the language in the error, however looking at the stack trace it is probably certificate related.

Try re-generating your certificate.
