### ISSUE TITLE
Array.Copy exception when queuing notifications on 3.0 dev branch

### ISSUE THREAD

**Issue by jjxtra** [Redth/PushSharp#615]
On the latest dev 3.0 branch, I'm also getting an error event very frequently about an Array.Copy not having a large enough destination array.

```
        private void Broker_iOS_OnNotificationFailed(ApnsNotification notification, Exception exception)
        {
            Logger.Log("Notification failed: {0}", exception);
        }
```

**Comment by Redth** [comment]
Please provide a stack trace... it's really difficult to track down an error without at least a stack trace :(

**Comment by jjxtra** [comment]
Ended up writing my own Apple provider and it's working. Sorry I don't have time to troubleshoot further.
