### ISSUE TITLE
WnsServiceConnection.Send is not thread safe

### ISSUE THREAD

**Issue by jackita** [Redth/PushSharp#619]
Hi all,

I notice that if I send more than one notification very close using the same instance of WnsServiceBroker, I get an error from Microsoft, it's status is "ChannelThrottled". Furthermore, if I instance a new WnsServiceBroker for each notification, all works fine.

**Comment by Redth** [comment]
This is interesting and weird.  I have tried a minor change (using a new instance of HttpClient for each notification), that's the only real 'difference' between creating a new broker instance i can think of.

**Comment by jackita** [comment]
Yes this works but it isn't a good solution because instance a new connection for each windows push notification. The matter is regarding the handling of GetAccessToken. Infact if you have multiple pushs to send you could have multiple call to the GetAccessToken that cause the failure.

**Comment by Redth** [comment]
@jackita I'm not sure what you mean.  There were some other changes to WNS to make the GetAccessToken method not called over and over.

**Comment by Redth** [comment]
I believe this is fixed, please ask to reopen if you believe otherwise.
