### ISSUE TITLE
Manage expired subscriptions in V3

### ISSUE THREAD

**Issue by 14skywalker** [Redth/PushSharp#620]
### What version of PushSharp are you using?
V3

### Describe your issue:
Is there a replacement for PushBroker_OnDeviceSubscriptionExpired

Best regards.

**Comment by Redth** [comment]
This really depends on each platform. Basically every platform except apple will provide this information in the OnNotificationFailed event (in the particular exception object for the platform).

For apple you still need to run the feedback service until HTTP/2 support returns.
