### ISSUE TITLE
How to listen events when sending a push notification

### ISSUE THREAD

**Issue by hemang-azilen** [Redth/PushSharp#624]
### What version of PushSharp are you using?
2.2

### Describe your issue:
I'm trying to receive a push notification from our server which uses PushSharp 2.2 to send push on iOS and Android devices. Android users are receiving push notifications but not in iOS. So for that, I want to listen for events which can be trigger in case of push failed.

**Following are the events which I supposed to handle:**

```
        public event ChannelCreatedDelegate OnChannelCreated;
        public event ChannelDestroyedDelegate OnChannelDestroyed;
        public event ChannelExceptionDelegate OnChannelException;
        public event DeviceSubscriptionChangedDelegate OnDeviceSubscriptionChanged;
        public event DeviceSubscriptionExpiredDelegate OnDeviceSubscriptionExpired;
        public event NotificationFailedDelegate OnNotificationFailed;
        public event NotificationRequeueDelegate OnNotificationRequeue;
        public event NotificationSentDelegate OnNotificationSent;
        public event ServiceExceptionDelegate OnServiceException;
```

### What are the steps required to reproduce this issue?

This is my code to send a push notification:

```
try
            {
                var push = new PushBroker();
                var serializer = new JavaScriptSerializer();

               
                    push.RegisterAppleService(new ApplePushChannelSettings(true, "Production Certificate here", "Certificate Password here"));         

                foreach (string item in IOSDeviceTokens)
                {
                    if(string.IsNullOrEmpty(item))
                        continue;                    

                    push.QueueNotification(new AppleNotification()
                                   .ForDeviceToken(item.ToString())
                                   .WithAlert(System.Net.WebUtility.HtmlDecode(NotificationText))
                                   .WithCustomItem("data", Newtonsoft.Json.JsonConvert.SerializeObject(IOSNotification))
                                   .WithSound("sound.caf")
                                   );

                    System.Threading.Thread.Sleep(50);  
                }
                
            }
            catch (Exception ex)
            {
                Logger.Error(ex);
            }

```

### Please provide any Exception Stack Traces

Please note that we've using (and setup) proper certificates. At iOS side, they have checked (by using NWPusher tool) to send a push on devices by selecting the same certificates.

So all good but still not able to receive a push.

We've tried sending push for about 100 times.

Is there a way that we can know what's the issue?

Any sample would be helpful.

Thanks!

**Comment by Redth** [comment]
You need to subscribe to the events you mentioned... 

I'm really not sure what you're asking here if you've done that.

Your code looks mostly correct except from i don't see you actually subscribing to any events, particularly the `OnNotificationFailed` event.
