### ISSUE TITLE
Unable to use PushBroker class

### ISSUE THREAD

**Issue by SalmanZahid** [Redth/PushSharp#625]
### What version of PushSharp are you using?
3.0
### Describe your issue:
When i am trying to use PushSharp in my application to send notification on Andriod i am unable to find  pushbroker class 
Please tell me quick solution, urgent required i will be highly thankful
![untitled](https://cloud.githubusercontent.com/assets/8514899/13330012/b763f176-dc18-11e5-8e38-9aa3632cae5d.png)

**Comment by Redth** [comment]
The singular PushBroker no longer exists in 3.0.

Please read this doc for more information on *why*:
https://github.com/Redth/PushSharp/wiki/Migrating-from-PushSharp-2.x-to-3.x#why-the-concept-of-a-single-broker-no-longer-exists
