### ISSUE TITLE
Cannot change scale before starting broker

### ISSUE THREAD

**Issue by NaNgets** [Redth/PushSharp#626]
There's no way to change scale before broker is started.

https://github.com/Redth/PushSharp/blob/master/PushSharp.Core/ServiceBroker.cs#L102

The `if` in the ChangeScale method which returns and breaks the method should be after the scale has been set.

**Comment by Redth** [comment]
Obviously the work around is to change the scale after you start it.  I will look at what's involved to be able to change before, but this is pretty minimally impactful.

Thanks for the report!
