### ISSUE TITLE
Folder HttpTwo was empty. 

### ISSUE THREAD

**Issue by wizard69software** [Redth/PushSharp#627]

**Comment by Redth** [comment]
It's a git submodule.

**Comment by wizard69software** [comment]
But in  .sln file you have a reference to  
HttpTwo\HttpTwo\HttpTwo.csproj

that not exist in .ZIP file

**Comment by Redth** [comment]
Right, so those projects aren't actually needed to compile, so I've removed them from the .sln.

You could have alternatively done a git checkout with submodules and they would exist.

Thanks
