### ISSUE TITLE
PushSharp on Cloud hosting

### ISSUE THREAD

**Issue by mushfiqweb** [Redth/PushSharp#63]
When I test in my local pc push notification works fine. But if  make it live by uploading to my cloud hosting, it gives the following error : 

The type initializer for 'PushSharp.PushService' threw an exception.\nInnerException: System.InvalidOperationException: Cannot perform CAS Asserts in Security Transparent methods

Testing URL : http://www.createplaydate.com.asp1-21.ord1-1.websitetestlink.com/api/PushNotificationIOS/SendNotification

I'm using RackSpace cloud hosting.

anyone have any idea about it ?
Thanks in advaced!

**Comment by lzoumas** [comment]
I know this is an old post, but were you ever to get this working on Rackspace Cloud Sites?

Thanks
