### ISSUE TITLE
Referenced assembly does not have a strong name

### ISSUE THREAD

**Issue by hubocan** [Redth/PushSharp#632]
### What version of PushSharp are you using?
PushSharp 3.0.1
### Describe your issue:
There is a warning after building of application which uses PushSharp 3:
Referenced assembly 'PushSharp.Core, Version=1.0.5895.6311, Culture=neutral, PublicKeyToken=null' does not have a strong name.
Referenced assembly 'PushSharp.Google, Version=1.0.5895.6313, Culture=neutral, PublicKeyToken=null' does not have a strong name.
### What are the steps required to reproduce this issue?
Use PushSharp 3 in a web application and build it.

**Comment by hubocan** [comment]
PushSharp 2.2.1 didn't have this issue. PushSharp 2.2.1 was updated to 3.0.1 using NuGet.

**Comment by hubocan** [comment]
Finally it is not working on the test server because:
Could not load file or assembly 'PushSharp.Google, Version=1.0.5895.6313, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required.

**Comment by Redth** [comment]
Currently I'm taking a stand against strong naming like so many others.... 
http://code972.com/blog/2014/04/68-ditching-strong-naming-for-lucene-net
http://strongnamingconsideredharmful.com/
https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/
http://www.outercurve.org/blog/2014/03/25/Strongnaming-I-Do-Not-Think-It-Means-What-You-Thin/

BUT if you must, try this: https://github.com/dsplaisted/strongnamer

**Comment by hubocan** [comment]
I think it is not a good approach. Previous version (2.x) was strong named so even later version of the same package should be. You should create a new NuGet package which would not be strong named and it will not collide with previous versions.
