### ISSUE TITLE
PushSharp.Android not exist at Version 3.0.1.0

### ISSUE THREAD

**Issue by samah2100** [Redth/PushSharp#633]
I installed PushSharp 3.0.1 using Install-Package PushSharp command

it installed successfully, but when I tried to suing PushSharp.Android namespace I got this error

The type or namespace name 'Android' does not exist in the namespace 'PushSharp' (are you missing an assembly reference?)

**Comment by hubocan** [comment]
It is refactored as PushSharp.Google.

**Comment by Redth** [comment]
This sounds like you are using code compiled against a 2.x version of PushSharp.  Make sure your code is not referencing the old version.  `PushSharp.Android` is not a namespace that appears in 3.x.
