### ISSUE TITLE
Migration from V2

### ISSUE THREAD

**Issue by tiwari-abhishek** [Redth/PushSharp#634]
### What version of PushSharp are you using?
V3
### Describe your issue:
Long story. Since the API doesnt support proxy configurations I had to modify the PushSharp source code to use it behind a proxy. Because of that I could not update to latest nugets since I have to track every change that happens in your library and make that change to my local code.

Now I have it deployed in production and we are facing frequent issues with Apple notifications. 

So as a last resort, I thought of falling back to using latest nugets(3.0). Returning to github I notice
a lot of files have been changed/removed in this version. Can you please provide a mapping of what class/method is renamed to what. Its a nightmare trying to port everything as so many files are renamed or removed and I am clueless as to what can be used as a replacement.

Would you be adding proxy support?

Thank you.

**Comment by Redth** [comment]
I do plan on eventually adding proxy support.  

I'm sorry but there's too many changes for me to provide you some sort of class / method mapping.  Look at the migration guide for a bit more info:  https://github.com/Redth/PushSharp/wiki/Migrating-from-PushSharp-2.x-to-3.x
