### ISSUE TITLE
voip push return exception InvalidToken

### ISSUE THREAD

**Issue by IAfanasov** [Redth/PushSharp#636]
### What version of PushSharp are you using?
3.0.1.0

### Describe your issue:
After sending voip push notification with voip token OnNotificationFailed event is fired and exception is "System.Exception: ErrorStatusCode: InvalidToken". Dosen PushSharp 3 support voip tokens at all?

**Comment by Redth** [comment]
You mean device tokens? Sure.  I'm not aware of any differences in device tokens for voip applications.

Are you sure you're using the right server (sandbox vs production) for which provisioning profile you used to sign the app which generated your device token?

**Comment by iospro** [comment]
Current new version of the PushSharp works with the previous push API (not HTTP2).
So I suppose that you need to allow validation for certificate names containing "VoIP Services:".
It seems that only new HTTP2 push API allows sending voip pushes using the common "Apple Push Services" certificate.

**Comment by denisdrake** [comment]
Let me add something regarding our situation

You have those checks in your code

Var issuerName = Certificate.IssuerName.Name;
              var commonName = Certificate.SubjectName.Name;

              if (!issuerName.Contains ("Apple"))
                  throw new ApnsConnectionException ("Your Certificate does not appear to be issued by Apple!  Please check to ensure you have the correct certificate!");
              if (!commonName.Contains ("Apple Push Services:")
                  && !commonName.Contains ("Website Push ID:"))
                  throw new ApnsConnectionException ("Your Certificate is not in the new combined Sandbox/Production APNS certificate format, please create a new single certificate to use");


We have the VOIP certificate with the 
issuerName = "1forma OOO"
SubjectName = "VoIP Services: ru.1forma.messenger"

So this is effectively will not pass your check, but we are using that certificate sending VOIP pushes via 2.* PushSharp

**Comment by IAfanasov** [comment]
@Redth we figured out solution. We have sol called voip pushes. The only difference i found between common pushes and voip pushes is certificate. Voip certificate don't pass certificate validation as @denisdrake pointed above. The value of SubjectName.Name property is "C=US, O=1forma OOO, OU=PE4356BW5G, CN=VoIP Services: ru.1forma.messenger, OID.0.9.2342.19200300.100.1.1=ru.1forma.messenger.voip". This string will fail in method CheckIsApnsCertificate line 96-98:

```
if (!Regex.IsMatch (commonName, "Apple.*?Push Services")
    && !commonName.Contains ("Website Push ID:"))
        throw new ApnsConnectionException ("Your Certificate is not a valid certificate for connecting to Apple's APNS servers");
```

Looks like apple is not firm on certificate subject name. What do you think about droping all check of Subject name at all? Just several days ago there were one more issue about certificates name: #641. Ready to remove this check myself if you agree.

**Comment by Redth** [comment]
It *does* seem like i'm losing the certificate validation battle.  The main reason I want to keep some checking is that this is where most people make a mistake in getting things setup.

I think I'll bring back the option of disabling the certificate check in the ctor.  At least that way you need to know what you're doing to bypass it...
