### ISSUE TITLE
Sending Push notification for multible device tokens

### ISSUE THREAD

**Issue by samah2100** [Redth/PushSharp#637]
I'm intending to use  PushSharp 3.0.1

### Describe your issue:
In [Rest Api](https://parse.com/docs/rest/guide) I could send the same notification to any device that its token in a specified list like that
```
"where": {
          "deviceToken": { "$in": ["XXX","ZZZ","XYZ"] }
        },
        "data": {
          "alert": "Giants scored against the A's! It's now 2-2."
        }
```
Could I do the same with PushSharp? How?

**Comment by Redth** [comment]
APNS does not support this. Just create and queue one notification for each device token. Just a simple loop. This is what the REST web service would have done for you creating the illusion that APNS supported this.
