### ISSUE TITLE
Is the Broker multi-threaded?

### ISSUE THREAD

**Issue by chemjournal** [Redth/PushSharp#639]
### What version of PushSharp are you using?
1.0.5908.27347

### Describe your issue:
I would like to know if I can have a singleton broker, or do I need to create one for every incoming request on the server? For it to be a singleton, does it work if multiple threads try to send notifications at the same time?

**Comment by Redth** [comment]
The broker is definitely thread safe, and you can set the number of threads it uses to process by changing its scale.  `myBrokerInstance.ChangeScale (2);`.  By default the scale is 1 (so a single thread is used), however even with 1 thread it's still safe to queue notifications from many different threads at the same time.
