### ISSUE TITLE
APNS Development certificate check in PushSharp 3.0.x

### ISSUE THREAD

**Issue by XabierGoros** [Redth/PushSharp#641]
Hello,

I'm using PushSharp 3.0.1.0 and I'm unable to load my Sandbox APNS development certificate once again with the new changed API. In the previous version I just had to add the `disableCertificateCheck` (remember [issue](https://github.com/Redth/PushSharp/pull/586#issuecomment-168679073)) flag to the Settings and that's all. In the current version it seems there is no way to disable that check and Apple always issues my Development certificate as "_Apple Development IOS Push Services_". However PushSharp always checks it:

```
if (!commonName.Contains ("Apple Push Services:")
                    && !commonName.Contains ("Website Push ID:"))
                    throw new ApnsConnectionException ("Your Certificate is not in the new combined Sandbox/Production APNS certificate format, please create a new single certificate to use");
```

I wouldn't want to use the new [combined certificate](https://github.com/Redth/PushSharp/issues/594) for security reasons. It is always good to separate the Production and Development certificates in different files and keep the Production in a secure vault.

Am I missing anything?

**Comment by XabierGoros** [comment]
Of course I forgot to say I wouldn't want to use the new [combined certificate](https://github.com/Redth/PushSharp/issues/594) for security reasons. It is always good to separate the Production and Development certificates in different files and keep the Production in a secure vault.

**Comment by Redth** [comment]
Commit d89a59d099b0cf9e099e3abe6a310e2591ce0bcf should fix this.  You weren't missing anything, and I have relented on the use case of giving out development only certificates as being useful :)

**Comment by XabierGoros** [comment]
Thanks! That's perfect Redth, I'll test it tomorrow and I'll give you a feedback, but those changes should fix it (although we have make you code those enemies called Regex!! ;-)

**Comment by Redth** [comment]
Aww. Someone has to love regex!!

**Comment by Redth** [comment]
So, the old style certs can now be safely used, plus there's now the ability to skip the validation logic altogether.

**Comment by XabierGoros** [comment]
When I said enemy I meant it because of their poor efficiency and not their difficulty (obviously your case is very simple one).

Jokes apart, I confirm you that the [v3.0.1.15](https://github.com/Redth/PushSharp/tree/3.0.1.15) you've just added works great using both kind of certificates. 

Thanks!

**Comment by Redth** [comment]
Thanks for confirming :)
