### ISSUE TITLE
Referenced assembly does not have a strong name

### ISSUE THREAD

**Issue by hubocan** [Redth/PushSharp#642]
### What version of PushSharp are you using?
PushSharp 3.0.1
### Describe your issue:
There is a warning after building of application which uses PushSharp 3:
 Referenced assembly 'PushSharp.Core, Version=1.0.5895.6311, Culture=neutral, PublicKeyToken=null' does not have a strong name.
 Referenced assembly 'PushSharp.Google, Version=1.0.5895.6313, Culture=neutral, PublicKeyToken=null' does not have a strong name.

Finally it is not working on the server because:
 Could not load file or assembly 'PushSharp.Google, Version=1.0.5895.6313, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required.
### What are the steps required to reproduce this issue?
Use PushSharp 3 in a web application and build it.

**Comment by hubocan** [comment]
I think it is not a good approach to stop strong naming in the middle of the process. Previous version (2.x) was strong named so even later version of the same package should be. You should create a new NuGet package which would not be strong named and it will not collide with previous versions.

BTW this breaking change is not mentioned in notes for migration from 2.x to 3.x.

StrongNamer is not a solution, because it is failing the build on the Visual Studio Team Services:
The "StrongNamer.AddStrongName" task failed unexpectedly.

**Comment by Redth** [comment]
Ok Ok Ok Ok, I relent ;)

Next release will be signed again, as much as it kills me to do it! 

Cheers!
