### ISSUE TITLE
APNS Feedback service

### ISSUE THREAD

**Issue by vplusm** [Redth/PushSharp#644]
### What version of PushSharp are you using?
3.0+

### Describe your issue:
How to use PushSharp with APNS feedback service. I need notification when token has expired. For example when user has removed an application. It works properly on Android (with PushSharp) but on iOS always returns success notification in PushSharp.

### What are the steps required to reproduce this issue?
Send push to device with uninstalled application. PushSharp will return success

**Comment by vplusm** [comment]
Do you use this new API ? For APNS
https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/APNsProviderAPI.html#//apple_ref/doc/uid/TP40008194-CH101-SW12

**Comment by Redth** [comment]
Here's how you would use the Feedback service in 3.x:

```csharp
var config = new ApnsConfiguration (
    ApnsConfiguration.ApnsServerEnvironment.Sandbox, 
    Settings.Instance.ApnsCertificateFile, 
    Settings.Instance.ApnsCertificatePassword);

var fbs = new FeedbackService (config);
fbs.FeedbackReceived += (string deviceToken, DateTime timestamp) => {
    // Remove the deviceToken from your database
    // timestamp is the time the token was reported as expired
};
fbs.Check ();
```
