### ISSUE TITLE
instal faild on .Net 4

### ISSUE THREAD

**Issue by ahmadrushdie** [Redth/PushSharp#648]
version 3.0.1.15

I am trying to install pushsharp  3.0.1.15 on .Net 4 using NuGet console its throw this 

Install failed. Rolling back...
Install-Package : Could not install package 'PushSharp 3.0.1.15'. You are trying to install this package into a project that ta
rgets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatib
le with that framework. For more information, contact the package author.
At line:1 char:16
+ Install-Package <<<<  PushSharp
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException

**Comment by Redth** [comment]
Correct. It requires 4.5 or higher.
