### ISSUE TITLE
Notifications doesn't reach

### ISSUE THREAD

**Issue by samah2100** [Redth/PushSharp#649]
### What version of PushSharp are you using?
3.0.1

### Describe your issue:

Notifications doesn't reach to the device although no exceptions thrown while sending the notifications, everything looks works fine, but the device didn't receive any notification

What are the possible reasons for that??

**Comment by SteRichardson** [comment]
Not sure if this will solve your problem, but we have had a similar issue recently when using the Sandbox ApnsServerEnvironment. 

The Apple Developer website lists the Application Services for your App ID, and ours was showing 'Enabled' for Distribution, but 'Configurable' for Development. It wants an entirely new certificate defining solely for Development use, but we're using the new Sandbox & Production 'Apple Push Services' certificate, so assumed it would be automatically assigned to both envionments - it's not.

We decided to just use the production certificate in development for now. Setting ApnsServerEnvironment to Production seems to work just fine.

**Comment by Redth** [comment]
@SteRichardson interesting and thanks for your input.  I have seen a few reports of this behaviour, but haven't been able to reproduce it myself.  I wonder if Apple has some bugs on their APNS servers when using the new combined certificate...

**Comment by sulkhayev** [comment]
@Redth , I have same issue. I downloaded APN Tester from AppStore and its working, but notification doesn't rich when using PushSharp.

**Comment by samah2100** [comment]
@SteRichardson Yes this was my case, but the certificate was for development while I was setting the ApnsServerEnvironment to Production. after changing it to sandbox it works fine
Thank you
