### ISSUE TITLE
Erro during compilation with VS2012

### ISSUE THREAD

**Issue by wizard69software** [Redth/PushSharp#652]
### What version of PushSharp are you using?
LAst versione .... 3.0
### Describe your issue:
During compilation VS2012 give this error ... and other

"char  $ not valid in .... " 

        public ApnsNotificationException (ApnsNotificationErrorStatusCode errorStatusCode, ApnsNotification notification)
            : base ($"Apns notification error: '{errorStatusCode}'")

**Comment by Redth** [comment]
This is a C# 6 feature which I'm guessing isn't even possible to use in VS2012... I thought I had removed instances of C# 6 being used.  I'll change this line and maybe it will let you compile.

**Comment by Redth** [comment]
Ok, 38c51c796de3bf32974b83287559ea0db99ebf2c removes this usage, please try again.
