### ISSUE TITLE
Can't found the old pushsharp 2 events

### ISSUE THREAD

**Issue by deserthero** [Redth/PushSharp#653]
### What version of PushSharp are you using?
PushSharp 3.0
### Describe your issue:

i didn't found the old PushSharp 2 events:
                    push.OnDeviceSubscriptionChanged
                    push.OnChannelException
                    push.OnServiceException
                    push.OnNotificationFailed
                    push.OnDeviceSubscriptionExpired
                    push.OnDeviceSubscriptionChanged
                    push.OnChannelCreated
                    push.OnChannelDestroyed

and i didn't founh in documentation how to replace them or how to use them in PushSharp 3, i only used:
`
                    apps["com.myapp"].Gcm.OnNotificationSucceeded += (notification) =>
                    {
                        log.Debug("Notification Sent To Android: -> " + notification);
                    };

                    apps["com.myapp"].Gcm.OnNotificationFailed += (notification, aggregateEx) =>
                    {

                        aggregateEx.Handle(ex =>
                        {

                            // See what kind of exception it was to further diagnose
                            if (ex is GcmConnectionException)
                            {
                                // Something failed while connecting (maybe bad cert?)
                                 log.Debug("Notification Failed (Bad Android Connection)!: " + ex.ToString());
                            }
                            else
                            {
                                log.Debug("Notification Failed (Android): " + ex.ToString());
                            }

                            // Mark it as handled
                            return true;
                        });
                    };
`
### What are the steps required to solve this?
Update the documentations

**Comment by Redth** [comment]
In 3.x, `OnNotificationFailed` will be called for the other cases that used to have separate events, you need to extract the relevant information from the exception.  This includes exceptions for registration expired/changed and any connection related exceptions.

There are no longer events for channels being created.

**Comment by deserthero** [comment]
How can i identify the types of exceptions that i should handle for every case.

For example in OnDeviceSubscriptionChanged can you put an simple example.

Also if you update the documentation with this it will be very helpful as it take from me along time to migrate from 2 to 3 cause the lake of documentations but finally i migrate correctly and post my answer here for any one need to migrate: http://stackoverflow.com/questions/35408704/production-certificate-error-in-push-notification-pushsharp/35651695#35651695

**Comment by Redth** [comment]
You will want to look for a `DeviceSubscriptonExpiredException` exception type in the `OnNotificationFailed` event's aggregate exception.

If the `DeviceSubscriptonExpiredException.NewSubscriptionId` is not null, it has changed and isn't just expired.

**Comment by deserthero** [comment]
Thanks :)

**Comment by Redth** [comment]
But you're right, I need to write better docs :)

**Comment by SumDa** [comment]
Hi Redth,
DeviceSubscriptonExpiredException had an typo that has been fixed to DeviceSubscriptionExpiredException. But still it is throwing the wrong type(older one) exception. So we are not able to use the newer exception type. Please see the attached screenshot.
![subscription](https://cloud.githubusercontent.com/assets/18167703/14143223/d49fa4a2-f6a7-11e5-98fa-a1edb26bfa46.png)
