### ISSUE TITLE
 can't  Receive  message

### ISSUE THREAD

**Issue by zhuyongwu** [Redth/PushSharp#654]
### Hello,  I created the certificate according to your steps,but  can't  Receive  message from APNS

,I have no error in running the project, ApnsServerEnvironment is Sandbox

How can I solve this problem, waiting for your reply, thank you very much!

**Comment by zhuyongwu** [comment]
Here's what I'm running.


waiting on tasks
apns_client[1]: sending batch id=1, count=1
apns_client[1]: sending batch id=1, count=1
apns_client[1]: sending batch id=1, count=1
apns_client[1]: sending batch id=1, count=1

**Comment by Redth** [comment]
It's telling you it failed.  You need to subscribe to the broker's `OnNotificationFailed` event and figure out why it failed (like in the README).

**Comment by zhuyongwu** [comment]
thank u very much!
