### ISSUE TITLE
Option to use a Proxy when connecting to Android

### ISSUE THREAD

**Issue by haythamsaleem** [Redth/PushSharp#658]
### Please provide any Exception Stack Traces
An error occurred while sending the request.
mscorlib
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PushSharp.Google.GcmServiceConnection.<Send>d__6.MoveNext()[[OnNotificationFailedEventGcmServiceBroker]]

Inner Exception details:

The remote name could not be resolved: 'gcm-http.googleapis.com'
System
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)

**Comment by haythamsaleem** [comment]
i have internet proxy on my server and GSM push sharp doesn't work when i try to sent to android device

**Comment by Redth** [comment]
There is no proxy support (yet).

**Comment by haythamsaleem** [comment]
thanks i solve the problem

**Comment by haythamsaleem** [comment]
to solve the problem i download the source code from github for version 3.0.1 and i update two files on project PushSharp.Google
1- i update on class as following Below 
using System;
using System.Net;

namespace PushSharp.Google
{
    public class GcmConfiguration
    {
        private const string GCM_SEND_URL = "https://gcm-http.googleapis.com/gcm/send";

        public GcmConfiguration (string senderAuthToken)
        {
            this.SenderAuthToken = senderAuthToken;
            this.GcmUrl = GCM_SEND_URL;

            this.ValidateServerCertificate = false;
        }

        public GcmConfiguration (string optionalSenderID, string senderAuthToken, string optionalApplicationIdPackageName)
        {
            this.SenderID = optionalSenderID;
            this.SenderAuthToken = senderAuthToken;
            this.ApplicationIdPackageName = optionalApplicationIdPackageName;
            this.GcmUrl = GCM_SEND_URL;

            this.ValidateServerCertificate = false;
        }

        public string SenderID { get; private set; }

        public string SenderAuthToken { get; private set; }

        public string ApplicationIdPackageName { get; private set; }

        public bool ValidateServerCertificate { get; set; }

        public string GcmUrl { get; set; }

        public void OverrideUrl (string url)
        {
            GcmUrl = url;
        }
        public void SetProxy(string proxyHost, int proxyPort)
        {
            UseProxy = true;
            ProxyHost = proxyHost;
            ProxyPort = proxyPort;
            ProxyCredentials = CredentialCache.DefaultNetworkCredentials;
        }

        public void SetProxy(string proxyHost, int proxyPort, string userName, string password, string domain)
        {
            UseProxy = true;
            ProxyHost = proxyHost;
            ProxyPort = proxyPort;
            ProxyCredentials = new NetworkCredential(userName, password, domain);
        }
        public bool UseProxy { get;  set; }

        public string ProxyHost { get;  set; }

        public int ProxyPort { get;  set; }

        public NetworkCredential ProxyCredentials { get;  set; }
    }
}

2- i update on GcmServiceConnectionFactory
using System;
using System.Threading.Tasks;
using System.Net.Http;
using System.Net.Http.Headers;
using Newtonsoft.Json.Linq;
using System.Net;
using PushSharp.Core;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Net.Sockets;
using System.Diagnostics;
using System.IO;

namespace PushSharp.Google
{
    public class GcmServiceConnectionFactory : IServiceConnectionFactory<GcmNotification>
    {
        public GcmServiceConnectionFactory(GcmConfiguration configuration)
        {
            Configuration = configuration;
        }

        public GcmConfiguration Configuration { get; private set; }

        public IServiceConnection<GcmNotification> Create()
        {
            return new GcmServiceConnection(Configuration);
        }
    }

    public class GcmServiceBroker : ServiceBroker<GcmNotification>
    {
        public GcmServiceBroker(GcmConfiguration configuration) : base(new GcmServiceConnectionFactory(configuration))
        {
        }
    }

    public class GcmServiceConnection : IServiceConnection<GcmNotification>
    {
        public GcmServiceConnection(GcmConfiguration configuration)
        {


            Configuration = configuration;
            if (Configuration.UseProxy)
            {
                http = getClientViaHTTPProxy(Configuration.ProxyHost, Configuration.ProxyPort);
            }
            else
            {
                http = new HttpClient();
            }
            http.DefaultRequestHeaders.UserAgent.Clear();
            http.DefaultRequestHeaders.UserAgent.Add(new ProductInfoHeaderValue("PushSharp", "3.0"));
            http.DefaultRequestHeaders.TryAddWithoutValidation("Authorization", "key=" + Configuration.SenderAuthToken);
        }

        public GcmConfiguration Configuration { get; private set; }

        readonly HttpClient http;

        public async Task Send(GcmNotification notification)
        {
            var json = notification.GetJson();

            var content = new StringContent(json, System.Text.Encoding.UTF8, "application/json");

            var response = await http.PostAsync(Configuration.GcmUrl, content);

            if (response.IsSuccessStatusCode)
            {
                await processResponseOk(response, notification);
            }
            else {
                var body = await response.Content.ReadAsStringAsync();
                processResponseError(response, notification);
            }
        }

        async Task processResponseOk(HttpResponseMessage httpResponse, GcmNotification notification)
        {
            var multicastResult = new GcmMulticastResultException();

            var result = new GcmResponse()
            {
                ResponseCode = GcmResponseCode.Ok,
                OriginalNotification = notification
            };

            var str = await httpResponse.Content.ReadAsStringAsync();
            var json = JObject.Parse(str);

            result.NumberOfCanonicalIds = json.Value<long>("canonical_ids");
            result.NumberOfFailures = json.Value<long>("failure");
            result.NumberOfSuccesses = json.Value<long>("success");

            var jsonResults = json["results"] as JArray ?? new JArray();

            foreach (var r in jsonResults)
            {
                var msgResult = new GcmMessageResult();

                msgResult.MessageId = r.Value<string>("message_id");
                msgResult.CanonicalRegistrationId = r.Value<string>("registration_id");
                msgResult.ResponseStatus = GcmResponseStatus.Ok;

                if (!string.IsNullOrEmpty(msgResult.CanonicalRegistrationId))
                    msgResult.ResponseStatus = GcmResponseStatus.CanonicalRegistrationId;
                else if (r["error"] != null)
                {
                    var err = r.Value<string>("error") ?? "";

                    msgResult.ResponseStatus = GetGcmResponseStatus(err);
                }

                result.Results.Add(msgResult);
            }

            int index = 0;

            //Loop through every result in the response
            // We will raise events for each individual result so that the consumer of the library
            // can deal with individual registrationid's for the notification
            foreach (var r in result.Results)
            {
                var singleResultNotification = GcmNotification.ForSingleResult(result, index);

                singleResultNotification.MessageId = r.MessageId;

                if (r.ResponseStatus == GcmResponseStatus.Ok)
                { // Success
                    multicastResult.Succeeded.Add(singleResultNotification);
                }
                else if (r.ResponseStatus == GcmResponseStatus.CanonicalRegistrationId)
                { //Need to swap reg id's
                    //Swap Registrations Id's
                    var newRegistrationId = r.CanonicalRegistrationId;
                    var oldRegistrationId = string.Empty;

                    if (singleResultNotification.RegistrationIds != null && singleResultNotification.RegistrationIds.Count > 0)
                        oldRegistrationId = singleResultNotification.RegistrationIds[0];

                    multicastResult.Failed.Add(singleResultNotification, new DeviceSubscriptonExpiredException
                    {
                        OldSubscriptionId = oldRegistrationId,
                        NewSubscriptionId = newRegistrationId
                    });
                }
                else if (r.ResponseStatus == GcmResponseStatus.Unavailable)
                { // Unavailable
                    multicastResult.Failed.Add(singleResultNotification, new GcmConnectionException("Unavailable Response Status"));
                }
                else if (r.ResponseStatus == GcmResponseStatus.NotRegistered)
                { //Bad registration Id
                    var oldRegistrationId = string.Empty;

                    if (singleResultNotification.RegistrationIds != null && singleResultNotification.RegistrationIds.Count > 0)
                        oldRegistrationId = singleResultNotification.RegistrationIds[0];

                    multicastResult.Failed.Add(singleResultNotification, new DeviceSubscriptonExpiredException { OldSubscriptionId = oldRegistrationId });
                }
                else {
                    multicastResult.Failed.Add(singleResultNotification, new GcmConnectionException("Unknown Failure: " + r.ResponseStatus));
                }

                index++;
            }

            // If we only have 1 total result, it is not *multicast*, 
            if (multicastResult.Succeeded.Count + multicastResult.Failed.Count == 1)
            {
                // If not multicast, and succeeded, don't throw any errors!
                if (multicastResult.Succeeded.Count == 1)
                    return;
                // Otherwise, throw the one single failure we must have
                throw multicastResult.Failed.First().Value;
            }

            // If we get here, we must have had a multicast message
            // throw if we had any failures at all (otherwise all must be successful, so throw no error
            if (multicastResult.Failed.Count > 0)
                throw multicastResult;
        }

        void processResponseError(HttpResponseMessage httpResponse, GcmNotification notification)
        {
            //401 bad auth token
            if (httpResponse.StatusCode == HttpStatusCode.Unauthorized)
                throw new UnauthorizedAccessException("GCM Authorization Failed");

            if (httpResponse.StatusCode == HttpStatusCode.BadRequest)
                throw new GcmConnectionException("HTTP 400 Bad Request");

            if ((int)httpResponse.StatusCode >= 500 && (int)httpResponse.StatusCode < 600)
            {
                //First try grabbing the retry-after header and parsing it.
                var retryAfterHeader = httpResponse.Headers.RetryAfter;

                if (retryAfterHeader != null && retryAfterHeader.Delta.HasValue)
                {
                    var retryAfter = retryAfterHeader.Delta.Value;
                    throw new RetryAfterException("GCM Requested Backoff", DateTime.UtcNow + retryAfter);
                }
            }

            throw new GcmConnectionException("GCM HTTP Error: " + httpResponse.StatusCode);
        }

        static GcmResponseStatus GetGcmResponseStatus(string str)
        {
            var enumType = typeof(GcmResponseStatus);

            foreach (var name in Enum.GetNames(enumType))
            {
                var enumMemberAttribute = ((EnumMemberAttribute[])enumType.GetField(name).GetCustomAttributes(typeof(EnumMemberAttribute), true)).Single();

                if (enumMemberAttribute.Value.Equals(str, StringComparison.InvariantCultureIgnoreCase))
                    return (GcmResponseStatus)Enum.Parse(enumType, name);
            }

            //Default
            return GcmResponseStatus.Error;
        }
        private HttpClient getClientViaHTTPProxy(string httpProxyHost, int httpProxyPort)
        {
            HttpClient client = null;
            try
            {
                string proxyUri =
                    string.Format("{0}:{1}", httpProxyHost, httpProxyPort);

                WebProxy proxy = new WebProxy(proxyUri, false)
                {
                    UseDefaultCredentials = true,
                };

                // Now create a client handler which uses that proxy


                HttpClientHandler httpClientHandler = new HttpClientHandler()
                {
                    Proxy = proxy,
                    PreAuthenticate = false,
                    UseDefaultCredentials = true,
                };
                client = new HttpClient(httpClientHandler);
            }
            catch (Exception ex)
            {
                client = null;
                Log.Error(ex.Message);
                throw;
            }
            return client;
        }
    }
}

i build solution and i use the DLL and its work fine :)
