### ISSUE TITLE
What's new in PushSharp 4.0?

### ISSUE THREAD

**Issue by memark** [Redth/PushSharp#659]
I just upgraded my system to PushSharp 3.0. Now I find that 4.0 has already been released. What were the changes? Should I try to upgrade right away while I'm at it?

**Comment by Redth** [comment]
It's a pretty small set of, yet breaking api changes.  I've refactored most of the exceptions to be subclassed from `NotificationException`, and most notably, renamed `GcmConnectionException` to `GcmNotificationException` and made it subclass `NotificationException` as well.

All of the current code in the readme and wiki should be based on 4.x

I'm trying to follow SemVer versioning now which means the major number gets bumped with any breaking api changes, no matter how few/small they are. 

So, yes, please update to 4.x
