### ISSUE TITLE
bug(documentation): example code not working

### ISSUE THREAD

**Issue by dylanvdmerwe** [Redth/PushSharp#660]
### What version of PushSharp are you using?
4.0

### Describe your issue:
Documentation does not compile for latest version of the library.
See screenshot below:
![capture](https://cloud.githubusercontent.com/assets/2852839/13986388/d95fe77e-f10a-11e5-846f-819f1b8a7bf6.JPG)

**Comment by Redth** [comment]
Fixed in 4.0.1.
