### ISSUE TITLE
Error on installing Package

### ISSUE THREAD

**Issue by sidneyhaddad** [Redth/PushSharp#661]
Hi there, I am trying to install under Visual Studio and I am getting this error:

PM> Install-Package PushSharp
Attempting to resolve dependency 'Newtonsoft.Json (≥ 7.0.1)'.
Installing 'PushSharp 4.0.0.0'.
Successfully installed 'PushSharp 4.0.0.0'.
Adding 'PushSharp 4.0.0.0' to MyVillage.Web.
Uninstalling 'PushSharp 4.0.0.0'.
Successfully uninstalled 'PushSharp 4.0.0.0'.
Install failed. Rolling back...
Install-Package : Could not install package 'PushSharp 4.0.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any 
assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package PushSharp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
 
Any advise?

## What version of PushSharp are you using?
Trying to install 4.0.0

### Describe your issue:
Can't intall the package

### What are the steps required to reproduce this issue?
Not sure.

### Please provide any Exception Stack Traces
No stack trace

**Comment by Redth** [comment]
Just like the error says, .Net 4.0 is not supported. You need .Net 4.5 or higher.
