### ISSUE TITLE
File version and product version aren't set in 4.0.1

### ISSUE THREAD

**Issue by lecamarade** [Redth/PushSharp#665]
In the latest nuget package dlls don't have proper versions.
I need to be able to use both 2.x and 4.x while migrating the code. Can't setup binding redirection without proper versions.

**Comment by Redth** [comment]
Will fix in 4.0.2.

**Comment by Redth** [comment]
4.0.4 should fix this.

**Comment by lecamarade** [comment]
Thank you!
