### ISSUE TITLE
OnNotificationFailed is being called with "DeviceSubscriptonExpiredException" which had a typo.

### ISSUE THREAD

**Issue by SumDa** [Redth/PushSharp#670]
### What version of PushSharp are you using?
PushSharp - 4.0.4
### Describe your issue:
OnNotificationFailed is being called with "DeviceSubscriptonExpiredException" which had a typo.
### What are the steps required to reproduce this issue?
check if(exception.InnerException is DeviceSubscriptionExpiredException), 
### Please provide any Exception Stack Traces
Please find the attached screenshot.
![subscription](https://cloud.githubusercontent.com/assets/18167703/14143513/47d77f66-f6a9-11e5-99f7-05236b80d0f7.png)

**Comment by Redth** [comment]
Thanks, this is fixed in f4073642598a2c2ee5feda857a4a988ff66f62c8
