### ISSUE TITLE
Sandbox/Prod odd behavior when development is not configured

### ISSUE THREAD

**Issue by bot2600** [Redth/PushSharp#673]
### What version of PushSharp are you using?
4.0.4 Nuget

### Describe your issue:
iOS, my bundle id only has push notifications configured for prod, it is still at Configurable in development. So there is no development push cert etc. When I pass in ApnsConfiguration.ApnsServerEnvironment.Production, I get InvalidToken. If I change it to ApnsConfiguration.ApnsServerEnvironment.Sandbox, the notification works as expected.

### What are the steps required to reproduce this issue?
Set up a new bundle id in developer.apple.com, leave development unconfigured for push, create cert for prod, load the prod cert and password into your app and try to send to production with nuget 4.0.4, receive token invalid error. switch to sandbox, notification succeeds

I havent tested the current code from source, I will be doing that this weekend.

Once I look at the code, I might see that this is convention based for the number of configured environments or something and cant be easily avoided, if so I will comment it and close the issue, but it might need documented.

### Please provide any Exception Stack Traces
{"Apns notification error: 'InvalidToken'"}
    Data: {System.Collections.ListDictionaryInternal}
    ErrorStatusCode: InvalidToken
    HResult: -2146233088
    HelpLink: null
    InnerException: null
    Message: "Apns notification error: 'InvalidToken'"
    Notification (PushSharp.Core.NotificationException): {{
  "aps": {
    "badge": 7
  }
}}

Update: this is pretty weird, looking at the code, it looks like everything is fine. The other odd piece is the same app is doing push notifications with 3.0 code, same bundle id and cert and everything is working fine.

**Comment by bot2600** [comment]
I am going to assume this is my issue until I can do more testing (and it probably is), so I am closing this

**Comment by mhoberhausen** [comment]
I'm having the same issue. Production doesn't work but the Sandbox version does...

**Comment by bot2600** [comment]
I think I tracked this down. I am making assumptions as it explains what I am seeing and I dont have a ton of experience with iOS apps. So take it all with a nice big grain of salt. The scheme I was using was doing debug more and not release locally, and it seems like that was enough to cause the app to register its device token with sandbox instead of production. I am assuming since I had push enable but not configured in dev, that it uses the same cert for both. When I archive, it works correctly, and change my scheme to a release scheme also causes it to work correctly.

Some one with a bit more iOS configuration knowledge may be able to come by and elaborate, but I think its working as designed.

**Comment by Redth** [comment]
Please keep this in mind, it may answer some of your questions:

A Device Token generated by an app signed with a Development Provisioning Profile is only valid for use with the Sandbox APNS server.

A Device Token generated by an app signed with an AdHoc or AppStore Provisioning Profile is only valid for use with the Production APNS server.

NOTE: Some users have reported issues with notification delivery using the combined Apple Push Notification service SSL (Sandbox & Production) certificate when trying to send notifications to the Sandbox APNS server.
