### ISSUE TITLE
Authentication failed because the remote party has closed the transport stream.

### ISSUE THREAD

**Issue by adelemam** [Redth/PushSharp#677]
v4.0

My service was running propoerly and one time it stopped working , was the exception 
InnerException = {"Authentication failed because the remote party has closed the transport stream."}

have no clue what happened, 

### Please provide any Exception Stack Traces
StackTrace = "   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)\r\n   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)\r\n   at System.Net.Security.SslSt...

**Comment by jilnesta** [comment]
I also the same exception. But I had tried rewoking with re-create p12 certificate it Okay. What is your OS receive PN ?

**Comment by faltintas** [comment]
Did you try to give permissions to IISUSR?
I solved same problem with this
http://stackoverflow.com/questions/2609859/how-to-give-asp-net-access-to-a-private-key-in-a-certificate-in-the-certificate

**Comment by adelemam** [comment]
its worked for me after lot of time regenerating certificate, I din't get it but it worked finall, 
thanks alot fo your cooperation
