### ISSUE TITLE
Notification.Tag probably shouldn't be serialized.

### ISSUE THREAD

**Issue by boazy** [Redth/PushSharp#678]
Currently Notification.Tag on all the different platforms has no [JsonIgnore] attribute and it actually gets serialized and sent to the Push Notification Service. This leads to subtle bugs, such as when you have some non-serializable attributes which just make Json.Net crash. It can also leak out unintended data, since users don't expect it to be sent to APNS/GCM/etc.

Is there a reason why no [JsonIgnore] attribute was added to this field?

**Comment by dylanvdmerwe** [comment]
This is actually a VERY good spot. I use the Tag object to hold a state. 

I actually am having an issue right now where if I provide a Tag, the GCMServiceBroker breaks and will not send messages or stop.

**Comment by Redth** [comment]
This is a great catch.  There is no need to serialize this property that I can think of.  If it's something you absolutely want to do, you can encapsulate the notification class inside of your own object.  I will be adding `[JsonIgnore]` to this property, thanks!

**Comment by dylanvdmerwe** [comment]
Awesome @Redth. Was just about to work on a pull request for it. If possible can this please be released as 4.0.5?

**Comment by Redth** [comment]
it will be in the very next release shortly.  

And to clarify, really only GcmNotification needs this treatment, as I don't use the json serializer for the other platforms.

Eventually Json.Net may be removed as a dependency, but for now this is a good change.

**Comment by boazy** [comment]
Thanks! That was quick. :)
