### ISSUE TITLE
Not an issue, just a question about Apple's feedback service.

### ISSUE THREAD

**Issue by lecamarade** [Redth/PushSharp#680]
### What version of PushSharp are you using?
4.0.4
I'm desperately trying to test the Feedback service.
I'm sending a hundred push notifications to the token that is no longer valid (the app has registered a new one). The FeedbackReceived never gets called. 

Any ideas why?
From you own experience, can you tell me what I need to do to make Apple consider the token invalid?

Sorry for offtopic.

**Comment by Redth** [comment]
Basically uninstalling an app, and then trying to use that token a few times should cause feedback...
