### ISSUE TITLE
Cannot create Production broker for new Apns certificate

### ISSUE THREAD

**Issue by chenar** [Redth/PushSharp#684]
### What version of PushSharp are you using?
4.0.10.0

### Describe your issue:
I used new type of Production&Sandbox certificate as below:
                try
                {
                    _pushBrokerIosProductionAndSandbox = new ApnsServiceBroker(new ApnsConfiguration(ApnsConfiguration.ApnsServerEnvironment.Production,
                        appleCertProductionAndSandbox,
                        ZLibNetworkPushConfig.instance.pushIosAppleCertificatePasswordProduction));
                }
                catch (Exception exception)
                {
                    ZDebug.Error(exception, "Broker creation was failed.");
                }

Got exception with message: "Specified argument was out of the range of valid values.\r\nParameter name: You are using a certificate created for connecting only to the Sandbox APNS server but have selected a different server environment to connect to."

### What are the steps required to reproduce this issue?
Just setup certificate as described in wiki than try to create broker with Production type and got the exception
### Please provide any Exception Stack Traces
at PushSharp.Apple.ApnsConfiguration.CheckIsApnsCertificate()\r\n   at PushSharp.Apple.ApnsConfiguration.Initialize(ApnsServerEnvironment serverEnvironment, X509Certificate2 certificate, Boolean validateIsApnsCertificate)\r\n   at PushSharp.Apple.ApnsConfiguration..ctor(ApnsServerEnvironment serverEnvironment, Byte[] certificateData, String certificateFilePwd)\r\n   at ZGLib.Network.Server.PushNotifications.ZPushNotificationsService..ctor() in ZPushNotificationsService.cs:line 63

**Comment by chenar** [comment]
I found option bool validateIsApnsCertificate to avoid validation. Haven't checked yet. But anyway, it is strange that certificate from instruction doesn't work

**Comment by Redth** [comment]
What is the common name on your certificate?

**Comment by chenar** [comment]
Common name is "Apple Development IOS Push Services: com.somecompany.someapp" it is new type of Sandbox&Production certificate.
Besides I've tested push notifications and Sandbox version came from sandbox server for both certificates but ad-hoc app version (signed with distribution certificate) doesn't receive neither from sandbox server nor from production server for Sandbox&Production certificate.
I you have any questions let me know please!

**Comment by Redth** [comment]
I don't think you actually created the new type of certificate then.  That one is just for Sandbox.

I just tried creating the new type again myself and I get a common name of `Apple Push Services: com.my.bundle.id` like the library is expecting.

**Comment by chenar** [comment]
Sorry for disturbing. It's my fault. Thank you for help and great solution! :)
