### ISSUE TITLE
iOS invalid token error

### ISSUE THREAD

**Issue by Greg4572** [Redth/PushSharp#686]
### What version of PushSharp are you using?

Have tried on Pushsharp v4.0.10
### Describe your issue:

I am trying to create a C# console application that use the ANPS sample code on the github page but when I run it, it fails and I get the 'Invalid token' error. I have checked and even recreated the sandbox certificates and provisioning profiles needed to create the device token that i use in the code but no matter what i do it still gives the error.

At the moment i am unsure if it is the certificate or the code that is giving me trouble.

Below i have inserted the code i am using. could you just look at it to see if is correct so i can rule it out as the cause of the problem. (it should be fine as it is your code that i haven't edited)

```
namespace PushTest
{
class Program
{
    static void Main(string[] args)
    {  
        // Configuration (NOTE: .pfx can also be used here)
        var config = new ApnsConfiguration(ApnsConfiguration.ApnsServerEnvironment.Sandbox,
            "path\ios_certificate.p12", "");

        // Create a new broker
        var apnsBroker = new ApnsServiceBroker(config);

        // Wire up events
        apnsBroker.OnNotificationFailed += (notification, aggregateEx) =>
        {

            aggregateEx.Handle(ex =>
            {

                // See what kind of exception it was to further diagnose
                if (ex is ApnsNotificationException)
                {
                    var notificationException = (ApnsNotificationException)ex;

                    // Deal with the failed notification
                    var apnsNotification = notificationException.Notification;
                    var statusCode = notificationException.ErrorStatusCode;


                    Console.WriteLine(notificationException);

                }
                else
                {
                    // Inner exception might hold more useful information like an ApnsConnectionException 

                    var notificationException = (ApnsNotificationException)ex;
                    // Deal with the failed notification
                    var apnsNotification = notificationException.Notification;
                    var statusCode = notificationException.ErrorStatusCode;

                    Console.WriteLine(apnsNotification);
                }
                // Mark it as handled
                return true;
            });
        };

        apnsBroker.OnNotificationSucceeded += (notification) =>
        {
            Console.WriteLine("Apple Notification Sent!");
        };

        // Start the broker
        apnsBroker.Start();

        // Queue a notification to send
        try
        {
            string[] tokens = new string[1] { "Device_Token" };
            foreach (var deviceToken in tokens)
            {
                // Queue a notification to send
                apnsBroker.QueueNotification(new ApnsNotification
                {
                    DeviceToken = deviceToken,
                    Payload = JObject.Parse("{\"aps\":{\"badge\":7}}")
                });
            }
        }
        catch (Exception ex)
        {
            Console.Write(ex);
        }
        // Stop the broker, wait for it to finish   
        // This isn't done after every message, but after you're
        // done with the broker
        apnsBroker.Stop();
    }
}
}
```

Any advice or help will be appreciated.

**Comment by lecamarade** [comment]
Are you sure the token you are using has been obtained from the same system?
I.e. if  you got it in prod and try it in sandbox, it won't work.

**Comment by Greg4572** [comment]
![capture](https://cloud.githubusercontent.com/assets/17877697/14699151/90f40bd6-0795-11e6-8e2b-9951a91e433b.PNG)
(blocked out my name for privacy)
![cert](https://cloud.githubusercontent.com/assets/17877697/14699030/9bde7974-0794-11e6-928d-7b428db73bbf.PNG)


Hi lecamarade, thanks for the reply. I am not sure what you meant by them being obtained from the same systems. Above i have attached images of the certificates from the Apple Developer website.
The first one (iOS Development) we use in our mobile app to create the token for the device, this gets inserted into a database on our server. The second one (APNs Development iOS) is the certificate that we use once the token has been created to send a push notification to the device the token comes from. The certificates are linked to each other  so i just dont know why i am still getting 'Invalid token' no matter what code i use. If there is something you can see that is wrong please let me know, i am just about ready to start breaking things trying to get this sorted.

**Comment by Redth** [comment]
Sounds like maybe this is your issue:

```
A Device Token generated by an app signed with a Development Provisioning Profile is only valid for use with the Sandbox APNS server.

A Device Token generated by an app signed with an AdHoc or AppStore Provisioning Profile is only valid for use with the Production APNS server.
```

**Comment by Greg4572** [comment]
That's the thing, the device token is created by a signed Development Provisioning Profile. (see attached image)
![profile](https://cloud.githubusercontent.com/assets/17877697/14708568/113159da-07cc-11e6-97e2-5217cfb16855.PNG)

When you create the certificates must both the APNs certificate and iOS developer certificate be created with the same certificate request and private key?

**Comment by Redth** [comment]
No, it just means that if you generate a device token in your app that was signed with a *development* provisioning profile, that token is only valid to be used with the *sandbox* apns server (using the development push certificate).... The opposite is true as well, if you generated a device token in your app that was signed with an *adhoc* or *appstore* provisioning profile, that token is only valid to be used with the production apns server (using the production push certificate).

**Comment by Greg4572** [comment]
I fully understand what you have said but it just doesn't work. Could it be because we are not importing/installing the certificates correctly? I am using a Windows PC so could it be that i am not importing/installing the certificates properly?

**Comment by lecamarade** [comment]
It has nothing to do with a WIndows PC. It's PushSharp, everybody uses a Windows PC if I were to guess. 
You may try to set your apns configuration to production. Just to give it a try. I'm sure the problem is in how you get you device tokens. Or... If it says the token is invalid maybe it is invalid. Do you truncate it by any chance in the db?

You can also try to debug PushSharp and see the actual response from Apple.

**Comment by Redth** [comment]
@Greg4572 if you can connect and send to APNS but get the invalid token error, the certs are probably ok, it is then one of a few issues.  The first most likely issue you are telling me is not the case, so the only other thing I can possibly think of is somehow your token is not formatted properly, or not obtained correctly.

Also @lecamarade lots of folks don't use Windows, in fact I do most of the development of PushSharp on a mac.

**Comment by lecamarade** [comment]
You mac people... :-)

**Comment by Greg4572** [comment]
@Redth We use a Phonegap plugin https://github.com/phonegap/phonegap-plugin-push to get the token. We don't change it in any way and it is immediately written to our database where it is stored. So the format should be fine.

**Comment by Redth** [comment]
What does the token string look like?  Fine for phone gap doesn't necessarily mean fine for pushsharp....

**Comment by lecamarade** [comment]
Do you have a phone to try with, to exclude possible issues with the 3rd
party?

**Comment by Greg4572** [comment]
hey this is what it loos like 25ecae810f942205eea959ed6bc0fd2435895d793526327a431d621f343ca1ee

**Comment by Redth** [comment]
Ok, that *looks* correct...   I'm not sure what else to tell you :/

**Comment by Greg4572** [comment]
Ok, well thanks anyway for the help i really appreciate it. Ill keep looking around and trying things. I will post here if i get it sorted.

**Comment by softwarea** [comment]
@Greg4572: Any progress on your side? 

I am having the exact the same problem as you. I have two production/AppStore certificates (one for the app and one for APNS). My app is published in the app store, but does not receive any push notifications. The server application that is firing the push notifications returns "Invalid token" (exactly as in your case) as error message (and my tokens look like the one that you posted a couple days ago).

My app is built with Telerik AppBuilder (so, it is based on Cordova/Phonegap).

I should mention that the push notifications are WORKING with develop provisioning profiles. It's just the production/AppStore version of my app that makes trouble ...

Currently I have no idea where to look for the problem ... Apple, Cordova, Telerik, PushSharp ...

@Redth: I assume you have no chance of returning a more detailed message than just "Invalid token"? It's probably exactly the message that Apple is returning, right?

Thanks for any help, guys! And thanks so much to Redth for providing such a great library!!

**Comment by Greg4572** [comment]
@softwarea Unfortunately still no luck on my end. One of my co-workers in giving it a go, ill let you know if we get it working.

**Comment by Krikroff77** [comment]
@Greg4572: Any progress ? I am having the same problem as you :(

Best regards.

**Comment by Greg4572** [comment]
@Krikroff77 Hi, unfortunately i have moved on to another project. I asked my co-worker who still does the mobile development and he still hasn't got it to work, so for now it isn't a high priority item to fix. If anything happens and we get it to work ill let you know.

**Comment by Krikroff77** [comment]
@Greg4572, thank you, i really appreciate :)

**Comment by ajeesh13** [comment]
Hi @Greg4572 ,
I have also faced this issue,But after one day search I can fix this issue.But even though pushsharp get into the success method,I didn't get the notification in my ipad. Anyway I have gone through the steps listed below.
1.Open the project in XCode.
2.Enable the push notification from Xcode
3.Second step will create an app id in apple developer console.
4.Upload the CSR certificate for the above app id.
5.Download the certificate.
6.Install the certificate in mac machine.
7.export  above certificate  from keychain access as p12 file
8.Use this file for c# application.

Hope this will help you

Thanks & Regards
Ajeesh

**Comment by Krikroff77** [comment]
@Greg4572, problem solved :) I migrated my project from Cordova to Xamarin and generated certificates on Mac OSX (before with openssl on win32), hope these informations can help !
Regards.

**Comment by Greg4572** [comment]
@Krikroff77 Hi, thanks ill look into what you have suggested.

**Comment by joaolori** [comment]
im facing same problem... Invalid Token
Can help»?

**Comment by mbachaalani** [comment]
Hello Guys,

There is a new option in XCode 8 where you put push notification on. It is set by default as false in XCode 8(in capabilities). Once you put it on make sure that you got a new Reg Id once you run the app based on your implementation on reg id saving in database. If it is on app start reload the app by clicking the app icon (ie not from background) just to make sure the reg id is updated. Then set in C# server code the alert property in payload JSON object.

Hope that helps.

**Comment by hualqueb** [comment]
Hi guys, I had the same problem. 

Apple just started to use the same certificate for Sandbox and Production, try change to Production the Apns Server Enviroment. This works for me.

> [https://support.verivo.com/hc/en-us/articles/216406423-Sandbox-and-Production-push-certificates-explained](url)

**Comment by jimiatworking** [comment]
Hey Guys, I have the same issue. And after I try many times that I found the issue because you're in debug mode and connect to your device to get the token. The main need to noticed, when you doing this way you need to turn your ApnsConfiguration.ApnsServerEnvironment to Sandbox, That means the APNS Production SSL certification only  work with Export with Singing Provisioning Profile and this will get the Production token to work with PushSharp. After I exported the .ipa and install through iTunes to device and the token works fine with PushSharp in ApnsConfiguration.ApnsServerEnvironment.Production enviroment.

**Comment by mociving** [comment]
Hi all, we faced the same issue and we found a solution that work for our environment.
We are using PushSharp 4.0.10 on the server side and the phonegap push plugin on the app side.
we are working on Sandbox environemnt (so compiling the app with Apple development profiles and using the flag ApnsConfiguration.ApnsServerEnvironment.Sandbox when creating the ApnsConfiguration on the server. Initially our push notification was alway failing with reason "Invalid Token".

The problem was related to a flag "IS_GCM_ENABLED" in the .plist file in the Xcode project that by Default is set to YES.
In this way, the phonegap plugin sent the Apple notifications through GCM and this was not working for our configuration. Setting the flag to NO, everything is working correctly. Hope this helps

**Comment by Greg4572** [comment]
@mociving Thanks for the reply, Ill pass your solution on to our developer.

**Comment by Greg4572** [comment]
Ok finally got this to work. Looks like it was the way i was creating the certificates was wrong. Here is the link to the article i used to create the certificates. [Link](http://www.grenadeco.com/tutorial/how-to-generate-apn-certificates-on-windows-using-openssl/). Hope this helps anybody stuck with the same issue.

**Comment by Pigsnuck** [comment]
This problem was caused for me because the device IDs were from the Sandbox and I was trying to use them to send production notifications. Hope this can help someone.

**Comment by umair-ali** [comment]
Guys, I"m getting same issue (Invalid Token) in console application on windows. Interesting thing is, certificate and device token are correct, as i'm able to send notification to device using below code, but not via PushSharp v4.0.10. Can anyone help me with this?

public static void PushMessage(string deviceID)
		{
			int port = 2195;
			String hostname = "gateway.push.apple.com";
			String certificatePath = SendPushNotificationPlayground.GetCertPath();
			X509Certificate2 clientCertificate = new X509Certificate2(System.IO.File.ReadAllBytes(certificatePath), SendPushNotificationPlayground.GetCertPassword());
			X509Certificate2Collection certificatesCollection = new X509Certificate2Collection(clientCertificate);

			TcpClient client = new TcpClient(hostname, port);
			SslStream sslStream = new SslStream(client.GetStream(), false, new RemoteCertificateValidationCallback(ValidateServerCertificate), null);

			try
			{
				sslStream.AuthenticateAsClient(hostname, certificatesCollection, SslProtocols.Tls, false);
				MemoryStream memoryStream = new MemoryStream();
				BinaryWriter writer = new BinaryWriter(memoryStream);
				writer.Write((byte)0);
				writer.Write((byte)0);
				writer.Write((byte)32);

				writer.Write(HexStringToByteArray(deviceID.ToUpper()));
				String payload = "{\"aps\":{\"alert\":\"" + "Hi,, This Is a Sample Push Notification For IPhone.." + "\",\"badge\":1,\"sound\":\"default\"}}";
				writer.Write((byte)0);
				writer.Write((byte)payload.Length);
				byte[] b1 = Encoding.UTF8.GetBytes(payload);
				writer.Write(b1);
				writer.Flush();
				byte[] array = memoryStream.ToArray();
				sslStream.Write(array);
				sslStream.Flush();
				client.Close();
			}
			catch (AuthenticationException ex)
			{
				Console.WriteLine($"AuthError: {ex.Message}");
				client.Close();
			}
			catch (Exception e)
			{
				Console.WriteLine($"Error: {e.Message}");
				client.Close();
			}

			Console.WriteLine("Direct::Sent");
		}

		public static bool ValidateServerCertificate(object sender,
											 X509Certificate certificate,
											 X509Chain chain,
											 SslPolicyErrors sslPolicyErrors)
		{
			if (sslPolicyErrors == SslPolicyErrors.None)
				return true;

			Console.WriteLine("Certificate error: " + sslPolicyErrors);

			// Do not allow this client to communicate with unauthenticated servers.
			return false;
		}

		public static byte[] HexStringToByteArray(string hexString)
		{
			byte[] HexAsBytes = new byte[hexString.Length / 2];
			for (int index = 0; index < HexAsBytes.Length; index++)
			{
				string byteValue = hexString.Substring(index * 2, 2);
				HexAsBytes[index] = byte.Parse(byteValue, NumberStyles.HexNumber, CultureInfo.InvariantCulture);
			}
			return HexAsBytes;
		}

**Comment by Greg4572** [comment]
Hey Umair,

Here is my code using PushSharp 4.0.10.
The way i use it is by passing this process a dataTable that has 2 columns (Tokens, Message). This is then processed and used to build the payload that is then sent to APNS. I hope this is helpful.



                   var config = new ApnsConfiguration(ApnsConfiguration.ApnsServerEnvironment.Production,
                        @"Path/to/cert", "password");
                    // Create a new broker
                    var apnsBroker = new ApnsServiceBroker(config);
                    // Wire up events
                    apnsBroker.OnNotificationFailed += (notification, aggregateEx) =>
                    {
                        aggregateEx.Handle(ex =>
                        {
                            // See what kind of exception it was to further diagnose
                            if (ex is ApnsNotificationException)
                            {
                                var notificationException = (ApnsNotificationException)ex;

                                // Deal with the failed notification
                                var apnsNotification = notificationException.Notification;
                                var statusCode = notificationException.ErrorStatusCode;

                                Console.WriteLine("Apple Notification Failed: " + apnsNotification + " : " + statusCode);
                            }
                            else
                            {
                                // Inner exception might hold more useful information like an ApnsConnectionException			
                                Console.WriteLine("Push notification failed for some unknown reason : " + ex);
                            }

                            // Mark it as handled
                            return true;
                        });
                    };

                    apnsBroker.OnNotificationSucceeded += (notification) =>
                    {
                        Console.WriteLine("Apple Notification Sent!");
                    };

                    // Start the broker
                    apnsBroker.Start();

                    var i = 0;

                    foreach (DataRow driOS in dataSet.Tables[1].Rows)
                    {
                       // loop for building list of tokens
                        var tokens = new List<string> {
                    
                        driOS[1].ToString()
                    };

                        foreach (var deviceToken in tokens)
                        {
                            // Queue a notification to send
                            apnsBroker.QueueNotification(new ApnsNotification
                            {
                                // Build payload with corresponding tokens and messages
                                DeviceToken = deviceToken,
                                Payload = JObject.Parse("{\"aps\" : { \"alert\" : { \"body\" : \"" + dataSet.Tables[1].Rows[i][0] + "\" }, \"badge\" : 1 },}")
                            });

                            i = i + 1;

                        }
                    }

                    // Stop the broker, wait for it to finish   
                    // This isn't done after every message, but after you're
                    // done with the broker
                    apnsBroker.Stop();
