### ISSUE TITLE
The name 'MY_REGISTRATION_IDS' does not exist in the current context

### ISSUE THREAD

**Issue by mxkeeper** [Redth/PushSharp#700]
### Code:CS0103 ERROR: The name 'MY_REGISTRATION_IDS' does not exist in the current context
![code_ issues](https://cloud.githubusercontent.com/assets/10997094/15159697/8f6c6e98-16fe-11e6-892d-a15a4a925c1a.png)

**Comment by Redth** [comment]
You need to create this yourself, the sample is just a suggestion.
