### ISSUE TITLE
Cannot build APNS for iOS device

### ISSUE THREAD

**Issue by marcbraun** [Redth/PushSharp#723]
### What version of PushSharp are you using?
4.0
### Describe your issue:
Building for an actual device other than the simulator produces this error:
**Error MT2002: Failed to resolve "System.Reflection.Emit.ILGenerator" reference from "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"**

### What are the steps required to reproduce this issue?
Run application on a iOS device

### Please provide any Exception Stack Traces
N/A

**Comment by mikocot** [comment]
Could you provide any information on what was the issue and how did you fix it?

**Comment by marcbraun** [comment]
Hi

All the sudden it worked properly.

Marc Braun
