### ISSUE TITLE
PushSharp - GCM Authorization Failed

### ISSUE THREAD

**Issue by ernieparrella** [Redth/PushSharp#775]
Using v4.0.10 of Pushsharp (nuget package), I am getting error "GCM Authorization Failed" when sending push notifications to Android devices. Seems the bug raised in issue 574 (#574 ) has been compiled into the nuget package, yet I'm still getting this error.

Could this be related to the introduction of Firebase Cloud Messaging?
Does anyone still have success using GCM?

**Comment by ernieparrella** [comment]
Using v4.0.10 of Pushsharp (nuget package), I am getting error "GCM Authorization Failed" when sending push notifications to Android devices. Seems the bug raised in issue 574 (https://github.com/Redth/PushSharp/issues/574 ) has been compiled into the nuget package, yet I'm still getting this error.

Could this be related to the introduction of Firebase Cloud Messaging?
Does anyone still have success using GCM?

**Comment by spstratis** [comment]
@ernieparrella GCM has been working fine for me using the current version of pushsharp.

**Comment by ernieparrella** [comment]
Thanks @spstratis for your comment - at least I know to pursue this issue with GCM and do not have to port across to Firebase Cloud Messaging just yet.

**Comment by ernieparrella** [comment]
The sender id used in the app code needs to match the sender id Firebase Cloud Message Console and its corresponding "Firebase Cloud Messaging token".
