### ISSUE TITLE
Sometimes APNS notifications aren't delivered

### ISSUE THREAD

**Issue by lecamarade** [Redth/PushSharp#779]
I have reports from customers that sometimes push notifications don't get delivered.
I checked push sharp logs and everything looks fine "APNS-Client[1]: Received -1 bytes response... ".

It's not really a PushSharp issue. More of a question if anybody had experienced something similar.
We checked the user device (push enabled, app closed, etc).

Does Apple guarantee a delivery? 

PushSharp #4.0.10

**Comment by SteveLobdell** [comment]
Apple guarantees a "best effort" attempt to deliver, so no.  Also, if they currently have your app open they will not receive the notification.  This is intentional by Apple.

**Comment by lecamarade** [comment]
Since iOS 10 the notification is always shown.
I believe my problem was tcp timeout in Azure: https://github.com/Redth/PushSharp/issues/744

**Comment by mbachaalani** [comment]
Hello,

You should use this server side library for push notification in c#:
https://github.com/bytefish/FcmSharp
The steps described to use it, includes a need to reference the serviceAccountKey.json file that is downloaded from the firebase console. This is the file that enables authentication on the channel. Without this enabling the notification sending is not reliable.
