### ISSUE TITLE
PushSharp GCM with Firebase Cloud Messaging

### ISSUE THREAD

**Issue by christophedellac** [Redth/PushSharp#787]
PushSharp version : 4.0

Hello community !

 I'm facing an issue after updating PushSharp to version 4 (previously was 1.0.8 or something). 

I did the update since apple change the famous "Apple Push Services" text and my notification were not working anymore. After a few modifications, my Apple pushes are working again, but this is not the case for Android's one.

I've read that Android also change a few things, integrating the Firebase Cloud Messaging, and I would like to know if anyone here have their android push notifications working without changing anything to their Android application (by that, I mean that you still have GCM instead of FCM).

Right now, I'm trying to send a push notification like this : 

                var configAndroid = new GcmConfiguration("My_app_id", "my_app_server_key_AIzaSyCp_...", "myAppName");`
                GlobalAndroidPush = new GcmServiceBroker(configAndroid);
                GlobalAndroidPush.OnNotificationFailed += blabla; // I have code here, just pointless to copy paste everything
                GlobalAndroidPush.OnNotificationSucceeded += blabla; // I have code here, just pointless to copy paste 

                GlobalAndroidPush.Start();
                GlobalAndroidPush.QueueNotification (new GcmNotification {
        RegistrationIds = new List<string> { 
            regId
        },
        Data = JObject.Parse ("{ \"title\" : \"Hello from heaven\" }")
    });
}

Executing that, it goes inside the OnNotificationSucceeded, but nothing is received to my device.

Any ideas on that ?

**Comment by ergunkocak** [comment]
Hello @christophedellac ,

Could you make it work? Like sending Apple notifications over Firebase.

Cheers
