### ISSUE TITLE
Pushnotification on production not delivered to ios devices 

### ISSUE THREAD

**Issue by AliYouness** [Redth/PushSharp#806]
Hi

can you help me out about ios device on production not receiving push notification . but push sharp server raise  send successful event. where is the problem ? the app is signed with production provisioning profile . first beginning all devices were getting after some time no device received ?

**Comment by oguzsezer** [comment]
I had the very same issue, so I implemented everything from scratch and found out that IIS was unable to load the certificate. So I changed LoadUserProfile to True at corresponding app pool's advanced settings. After that my implementation started working. Then I tested with pushsharp, and it started working as well.
Please see this answer on stackoverflow, this is exactly what was happening behind the scenes but pushsharp wasn't complaining about: http://stackoverflow.com/questions/17149132/what-exactly-happens-when-i-set-loaduserprofile-of-iis-pool
Hope this will help someone.

PS: It was working smoothly in my local (win10), but not working on server (IIS8).

**Comment by v-tsymbalistyi** [comment]
Any updates on this? Have the same issue.

**Comment by hamzauzumcu** [comment]
you can use development.cer and development.p12 file. 
I fixed my issue. if you release your app, you can use pro.cer and pro.p12 file

**Comment by lakshaydulani** [comment]
@v-tsymbalistyi what did u do to fix the issue?

**Comment by v-tsymbalistyi** [comment]
@lakshaydulani nothing actually.
I upgraded a library to the newest version and forgot to call Start method on a service broker.)
So I was putting notifications into a queue but they were never sent since the broker had been never started.
