### ISSUE TITLE
APNS Notification not working suddenly.

### ISSUE THREAD

**Issue by ghousester** [Redth/PushSharp#807]
### What version of PushSharp are you using? PushSharp 4.0.10

We have an azure website hosted. We are sending push notification through this webapp, basically a web api. I configured certificate as per the suggestion given, and configured for Production. This api is HTTPS enabled. Everything seemed to be working fine before 10 days. Suddenly we are getting issue while delivering the push notification for IOS devices through APNS.

The same message and same code works perfectly in local, using a console app. Looks like the issue is with the SslProtocols set in, stream.AuthenticateAsClient (Configuration.Host, certificates, System.Security.Authentication.SslProtocols.Tls, false);

Can you please make this working??

Below is the sample code used,

private static void SendNotificationToIos()
        {
            var appleCert = File.ReadAllBytes(@"F:\Project-Samples\PushNotificationTest\PushNotificationTest\bin\Debug\xxxxx.p12");
            var config = new ApnsConfiguration(ApnsConfiguration.ApnsServerEnvironment.Production, appleCert, "xxxxx");

            // Create a new broker
            var apnsBroker = new ApnsServiceBroker(config);

            // Wire up events
            apnsBroker.OnNotificationFailed += (notification, aggregateEx) =>
            {
                aggregateEx.Handle(ex =>
                {
                    // See what kind of exception it was to further diagnose
                    if (ex is ApnsNotificationException)
                    {
                        var notificationException = (ApnsNotificationException)ex;
                        // Deal with the failed notification
                        var apnsNotification = notificationException.Notification;
                        var statusCode = notificationException.ErrorStatusCode;
                        //Console.WriteLine ($"Apple Notification Failed: ID={apnsNotification.Identifier}, Code={statusCode}");

                    }
                    else
                    {
                        // Inner exception might hold more useful information like an ApnsConnectionException           
                        //Console.WriteLine ($"Apple Notification Failed for some unknown reason : {ex.InnerException}");
                    }
                    return true;
                });
            };

            apnsBroker.OnNotificationSucceeded += (notification) =>
            {
                Console.WriteLine("Apple Notification Sent!");
            };
            var MY_DEVICE_TOKENS = new List<string>() { "6ec249cba4025d6f6729c0be513e601c1b88cb74b3ccfad3d0246a929deedfab" };
            var messageObj =
                           "{\"aps\":{\"alert\":\"My test message\",\"badge\":2,\"sound\":\"sound.caf\"},\"messageId\":\"953256\",\"message\":\"My test message\",\"type\":\"AAA\",\"entityid\":\"286818\",\"userid\":\"40642\"}";
            foreach (var deviceToken in MY_DEVICE_TOKENS)
            {
                apnsBroker.Start();
                // Queue a notification to send
                apnsBroker.QueueNotification(new ApnsNotification
                {
                    DeviceToken = deviceToken,
                    Payload = JObject.Parse(messageObj)
                });
                apnsBroker.Stop();
            }
        } 

### Please provide any Exception Stack Traces
PushSharp.Apple.ApnsNotificationException: Apns notification error: 'ConnectionError' ---> PushSharp.Apple.ApnsConnectionException: SSL Stream Failed to Authenticate as Client ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The message received was unexpected or badly formatted
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncReques

**Comment by sbryfcz** [comment]
Same issue.

**Comment by oopee** [comment]
Check the validity of the p12 certificate. I got this error after my certificate had expired (which caused SSL connection to fail).
