### ISSUE TITLE
Apns notification error: 'ConnectionError'

### ISSUE THREAD

**Issue by sercanparker** [Redth/PushSharp#839]
### What version of PushSharp are you using?
4.0.10 from Nuget Package Service.
### Describe your issue:
Almost 2 weeks ago there is no any issue about iOS push notifications, they were working as well as GCM push notification service not only localhost but also Azure Deploy too. However, suddenly library started give exception for APN service as written under Exception Stack Traces title. I know it's looks like magic but sometimes it's working sometimes not working. By the way, GCM is working perfectly. I want to implement static situation about iOS push notification but it's not working as before.
### Please provide any Exception Stack Traces
System.AggregateException: One or more errors occurred. ---> PushSharp.Apple.ApnsNotificationException: Apns notification error: 'ConnectionError' ---> PushSharp.Apple.ApnsConnectionException: Failed to Connect, check your firewall settings! ---> System.Net.Sockets.SocketException: No such host is known     at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)     at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)     at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)  --- End of stack trace from previous location where exception was thrown ---     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     at PushSharp.Apple.ApnsConnection.<connect>d__25.MoveNext()     --- End of inner exception stack trace ---     at PushSharp.Apple.ApnsConnection.<connect>d__25.MoveNext()  --- End of stack trace from previous location where exception was thrown ---     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)     at PushSharp.Apple.ApnsConnection.<SendBatch>d__21.MoveNext()     --- End of inner exception stack trace ---     at PushSharp.Apple.ApnsServiceConnection.<Send>d__2.MoveNext()     --- End of inner exception stack trace ---  ---> (Inner Exception #0) PushSharp.Apple.ApnsNotificationException: Apns notification error: 'ConnectionError' ---> PushSharp.Apple.ApnsConnectionException: Failed to Connect, check your firewall settings! ---> System.Net.Sockets.SocketException: No such host is known     at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)     at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)     at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)  --- End of stack trace from previous location where exception was thrown ---     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     at PushSharp.Apple.ApnsConnection.<connect>d__25.MoveNext()     --- End of inner exception stack trace ---     at PushSharp.Apple.ApnsConnection.<connect>d__25.MoveNext()  --- End of stack trace from previous location where exception was thrown ---     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)     at PushSharp.Apple.ApnsConnection.<SendBatch>d__21.MoveNext()     --- End of inner exception stack trace ---     at PushSharp.Apple.ApnsServiceConnection.<Send>d__2.MoveNext()<---

**Comment by adammendoza** [comment]
Any fix?

**Comment by sercanparker** [comment]
When I follow these instructions for Azure configuration, It was fixed.
https://github.com/Redth/PushSharp/wiki/Configuring-a-certificate-for-APNS-on-the-Azure-platform
