### ISSUE TITLE
ApplePushChannel not sending notifications

### ISSUE THREAD

**Issue by Matthewh66** [Redth/PushSharp#85]
Hello,

Sorry to bother you again - another quick question if I may.  I'm developing an app to submit message to apple.

In my PushServiceSettings I've set the MaxAutoScaleChannels to be 1. Occasionally, normally after a period of inactivity, when I try to send a message the push service fails to queue the notification (the notification never arrives and the SendSuccess or SendFailure event handlers never fire ). There is no exception rasied, and the ChannelDestroyed event has never fired either.

Do you know of any problem with setting MaxAutoScaleChannels = 1. All other settings are the default ones.

Kind regards
M

**Comment by perlasivakrishna** [comment]
Hi Redth..
 i am still facing the problem with old files. i am not able see the files in this link ( https://dl.dropbox.com/u/56106/PushSharp-Preview-20130128-0933.zip ) can you please send me 3.0 version PushSharp.dll files.
Thanks in advance.

**Comment by Redth** [comment]
3.0 releases are available as pre-release packages on Nuget.org.

**Comment by ABSingl** [comment]
Hi Redth..
I am using Pushsharp 4.0.10 and using the Apple production certificate to push notifications , what is happening notification is received sometimes and sometimes it missed to reach to production device.
Everything is verified that is we are using Apple production ceritificate, device token are from production environment. Can you please let me know reason behind missing of notifications some time.
Though when we tested on development server it works fine with no notification missed.
Here is my code.
Thanks in advance

 public void PushBroker(ApnsConfiguration config, string notMessage, int notId, string deviceToken)
        {
            #region PushBroker
            var apnsBroker = new ApnsServiceBroker(config);
            // Create a new broker


            // Wire up events
            apnsBroker.OnNotificationFailed += (notification, aggregateEx) =>
            {

                aggregateEx.Handle(ex =>
                {

                    // See what kind of exception it was to further diagnose
                    if (ex is ApnsNotificationException)
                    {
                      

                    }
                    else {
 
                    }

                    // Mark it as handled
                    return true;
                });
            };

            apnsBroker.OnNotificationSucceeded += (notification) =>
            {
                
            };

            // Start the broker
            apnsBroker.Start();
            string appleJsonFormat = "{\"aps\": {\"alert\":" + '"' + notMessage + '"' + ",\"sound\": \"default\"}}";

            apnsBroker.QueueNotification(new ApnsNotification
            {
                DeviceToken = deviceToken,
                Payload = JObject.Parse(appleJsonFormat)
            });


            // Stop the broker, wait for it to finish   
            // This isn't done after every message, but after you're
            // done with the broker
            apnsBroker.Stop();
            #endregion PushBroker
        }
