### ISSUE TITLE
Apns notification error: 'ConnectionError'

### ISSUE THREAD

**Issue by ranouf** [Redth/PushSharp#863]
Hi,

I read:
https://github.com/Redth/PushSharp/issues/706
https://github.com/Redth/PushSharp/issues/837
https://github.com/Redth/PushSharp/issues/850

I have the same error, but I didnt find in these answers any solution which can help me.

I have an Asp.Net Core web Api which is supposed to send PushNotification to IOS.

I just copy paste the code from here:
https://github.com/Redth/PushSharp/

```
// Configuration (NOTE: .pfx can also be used here)
var config = new ApnsConfiguration (ApnsConfiguration.ApnsServerEnvironment.Sandbox, 
    "[PATH TO P12]", "[PWD]");

// Create a new broker
var apnsBroker = new ApnsServiceBroker (config);
    
// Wire up events
apnsBroker.OnNotificationFailed += (notification, aggregateEx) => {

	aggregateEx.Handle (ex => {
	
		// See what kind of exception it was to further diagnose
		if (ex is ApnsNotificationException) {
			var notificationException = (ApnsNotificationException)ex;
			
			// Deal with the failed notification
			var apnsNotification = notificationException.Notification;
			var statusCode = notificationException.ErrorStatusCode;

			Console.WriteLine ($"Apple Notification Failed: ID={apnsNotification.Identifier}, Code={statusCode}");
	
		} else {
			// Inner exception might hold more useful information like an ApnsConnectionException			
			Console.WriteLine ($"Apple Notification Failed for some unknown reason : {ex.InnerException}");
		}

		// Mark it as handled
		return true;
	});
};

apnsBroker.OnNotificationSucceeded += (notification) => {
	Console.WriteLine ("Apple Notification Sent!");
};

// Start the broker
apnsBroker.Start ();

	// Queue a notification to send
	apnsBroker.QueueNotification (new ApnsNotification {
		DeviceToken = [DEVICETOKEN],
		Payload = JObject.Parse ("{\"aps\":{\"badge\":7}}")
	});

   
// Stop the broker, wait for it to finish   
// This isn't done after every message, but after you're
// done with the broker
apnsBroker.Stop ();
```

If I change "ApnsConfiguration.ApnsServerEnvironment.Sandbox" to ApnsConfiguration.ApnsServerEnvironment.Production" I have an error saying that the P12 is only for Sandbox, it means that the P12 certificate file is read correctly.

Each time I execute this sample code, I get this error: Apns notification error: 'ConnectionError'

I dont know how to solve it. 

Is there someone who knows and can help me?

Here is the branch where I tested it:
https://github.com/ranouf/AspNetCore-Angular-AllInOne/tree/TestPushNotification
Here is the PushNotificationService:
https://github.com/ranouf/AspNetCore-Angular-AllInOne/blob/TestPushNotification/src/server/AllInOne.Infrastructure/PushNotification/PushNotificationService.cs
And here is where I call it:
https://github.com/ranouf/AspNetCore-Angular-AllInOne/blob/TestPushNotification/src/server/AllInOne.Api/Controllers/Samples/SampleController.cs

**Comment by ranouf** [comment]
Today, it s working without any modification in the code or the network.
I dont know why he didn t work yesterday.

**Comment by git-pachie** [comment]
aggregateEx.Handle (ex => {
	
		// See what kind of exception it was to further diagnose
		if (ex is ApnsNotificationException) {
			var notificationException = (ApnsNotificationException)ex;
			
			// Deal with the failed notification
			var apnsNotification = notificationException.Notification;
			var statusCode = notificationException.ErrorStatusCode;

			Console.WriteLine ($"Apple Notification Failed: ID={apnsNotification.Identifier}, Code={statusCode}");
	
		} else {
			// Inner exception might hold more useful information like an ApnsConnectionException			
			Console.WriteLine ($"Apple Notification Failed for some unknown reason : {ex.InnerException}");
		}

		// Mark it as handled
		return true;
	});

This code does not compile to me
I am using VS2015. .net 4.6.2
