### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by SeppPenner** [Redth/PushSharp#906]
Is this repository still maintained?

**Comment by SeppPenner** [comment]
Seems like it's not.

**Comment by sonergonul** [comment]
No. @Redth is quite bussy in these days.

**Comment by SeppPenner** [comment]
I already assumed that. I will take [SignalR](https://docs.microsoft.com/en-US/aspnet/signalr/overview/getting-started/introduction-to-signalr) for that.
