### ISSUE TITLE
Error=DeprecatedEndpoint

### ISSUE THREAD

**Issue by MostafaSholkany** [Redth/PushSharp#907]
I use version of 4.0.10
i try to push from backend (asp.net web api) to android 
gcmBroker respond with exception  
400 HTTP bad request (Error=DeprecatedEndpoint)
what is happen?

**Comment by hakkiyagiz** [comment]
Google actually pulled the plug of GCM service at 6th Aug 2019

**Comment by hakkiyagiz** [comment]
You should use override method for changing endpoint of GCM service to FCM

PushSharp.Google/GcmConfiguration.cs
`
public void OverrideUrl (string url)
        {
            GcmUrl = url;
        }
`

Ex:
`var conf = new GcmConfiguration("optionalSenderID", "senderAuthToken", null);
conf.OverrideUrl("https://fcm.googleapis.com/fcm/send");
return conf;`

**Comment by MostafaSholkany** [comment]
@hakkiyagiz  
worked successfully  
thank you for helping me
